### ISSUE TITLE
Undefined variable _server ?

### ISSUE THREAD

**Issue by webzstore-sahel** [vqmod/vqmod#104]
I have installed vqmod successfully on opencart 2.1.0.1. The frontend is coming nice. But when trying to access admin, it is giving us following errors...

Notice: Undefined variable: _SERVER in /home/myorga8/public_html/vqmod/vqcache/vq2-system_startup.php on line 70
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/myorga8/public_html/vqmod/vqcache/vq2-system_startup.php:70) in /home/myorga8/public_html/system/library/session.php on line 21Notice: Undefined index: HTTPS in /home/myorga8/public_html/BanglADM19s5/controller/common/header.php on line 6

To resolve above issue I commented the line error_reporting(E_ALL); in the vq2-system_startup.php. But after some time it is overwritten by system itself and start showing the error again.

How to fix this error. Any guide will be appreciated.
Thanks.

**Comment by JAY6390** [comment]
This is not a vqmod issue. To resolve it, create a vqmod xml file to rewrite that line, or edit the original file system/startup.php in your opencart to the fixed version

**Comment by webzstore-sahel** [comment]
Thanks for your guide.
