### ISSUE TITLE
error 500 pop up on basic install of opencart Version 2.3.0.2

### ISSUE THREAD

**Issue by jasonc310771** [vqmod/vqmod#105]
Hi,  I have noticed after installing a fresh copy of opencart Version 2.3.0.2 and removing all default items and settings to allow me to add my own items and the categories that the cart fails a lot with a popup error 500.  At first that it was something i had caused.  So I deleted the whole site and started again but left everything alone, default install, with its items.  I added vqmod-2.6.1-opencart and vqmod_manager-master and started to get the error 500 immediately on loading the home page or the admin pages.
I checked the cpanel stats and the virtual memory is over 2gig.  I asked my cloud host to increase this and they set it to 6gig and I get to 4gig used in some cases.

Is this something that is know ?

**Comment by JAY6390** [comment]
Try a fresh install with just VQMod. VQMod manager is not part of the core VQMod and isn't something we provide support for. I cannot reproduce your issue either. We test the latest vqmod on all the latest opencart versions (clean installs) to see if they break

**Comment by jasonc310771** [comment]
I tried that and still I am facing the same issue. (fresh install with just VQMod, no change to the default install with default items.  Still facing error 500 pop up in admin and main home page or any other page.

**Comment by JAY6390** [comment]
There must be a configuration issue, either with PHP or apache itself. These definitely don't have an issue running together. Perhaps you have a missing php extension such as DOMDocument. Contact your host and ask them to take a look at the error logs for both apache and php

**Comment by jasonc310771** [comment]
After many chat sessions the host has decided to rebuild the server from scratch as it seems we were all right that it could not possibilly be the software issue as many 1000's use it every day and with out this sort of issue.  Will close this thread and if needed reopen it should I face this issue again (which I do not expect to be doing anytime soon!)
