### ISSUE TITLE
Bug when creating a product

### ISSUE THREAD

**Issue by vynnus** [vqmod/vqmod#106]
I've Installed vqmod 3.6.1 on a fresh install of opencart 2.2.0.0

On admin go to Catalog / Products

When you hit the Add new product button a random product is auto created, the page is reloaded back to products list generating a random product name

It`s just not possible to create a new product.

**Comment by JAY6390** [comment]
This is not a bug with the VQMod engine which is what this issue section is for. You're describing a bug that is from an extension you've purchased that utilises the VQMod engine and need to contact them about this
