### ISSUE TITLE
Problem with .php file on vqmod

### ISSUE THREAD

**Issue by Fluuxx** [vqmod/vqmod#11]
Hello ther,
i've installed vqmod on my opencart site following your steps but when i try to access to my domain i see an error like this :

Fatal error: Cannot redeclare Loader::__get() in /home/thepeach/public_html/vqmod/vqcache/vq2-system_engine_loader.php on line 22

How can i risolve this?

**Comment by varsha63** [comment]
i having a same issue after installed vqmod what to do please give brief solution
