### ISSUE TITLE
install/index.php is in the Opencart Branch but not in the tagged release

### ISSUE THREAD

**Issue by StyxOfDynamite** [vqmod/vqmod#111]
Hi,

Not sure if I'm missing something here but latest opencart-tagged release doesn't seem to have the required files for installation ? I've just downloaded and unzipped and this is the resulting directory structure. 

```
~/Desktop                                                                                                                                                                  
▶ unzip vqmod-2.6.2-opencart.zip 
Archive:  vqmod-2.6.2-opencart.zip
cc57161e73442fca6ebdfebc1db418fe090b5e85
   creating: vqmod-2.6.2-opencart/
  inflating: vqmod-2.6.2-opencart/README.md  
  inflating: vqmod-2.6.2-opencart/vqmod.xsd  
   creating: vqmod-2.6.2-opencart/vqmod/
  inflating: vqmod-2.6.2-opencart/vqmod/.htaccess  
   creating: vqmod-2.6.2-opencart/vqmod/install/
 extracting: vqmod-2.6.2-opencart/vqmod/install/.htaccess  
  inflating: vqmod-2.6.2-opencart/vqmod/install/ugrsr.class.php  
  inflating: vqmod-2.6.2-opencart/vqmod/pathReplaces.php  
  inflating: vqmod-2.6.2-opencart/vqmod/readme.txt  
  inflating: vqmod-2.6.2-opencart/vqmod/vqmod.php 
```

**Comment by qphoria** [comment]
Fixed in new 2.6.3 release.

**Comment by StyxOfDynamite** [comment]
As a point of interest, how is the release tagged as > 25 days old yet it wasn't cut 6 days when I raised the issue?

**Comment by qphoria** [comment]
Not sure I follow. The only things I see > 25 day old are the files that weren't changed today. Only the vqmod_opencart.xml file was changed today and has a time of less than 1 hour currently

**Comment by StyxOfDynamite** [comment]
![screenshot_20170717-200540](https://user-images.githubusercontent.com/946550/28285139-7631b910-6b2b-11e7-97ff-4d6071bb67c5.png)

I figured tagging a release made a commit that was used for release date but I'm obviously mistaken

**Comment by StyxOfDynamite** [comment]
Nice work on getting it sorted anyway. Much confusion when client is saying install instructions worked and deployed mod file wasn't doing anything.

**Comment by qphoria** [comment]
Ah ok.. that is because I just renamed the 2.6.2 entry on that page to 2.6.3 since 2.6.2 was bad anyway
But I corrected the tag to point to the correct base

**Comment by StyxOfDynamite** [comment]
I got you.
