### ISSUE TITLE
Version number didn't get changed in 2.6.3

### ISSUE THREAD

**Issue by tdaubs** [vqmod/vqmod#113]
Tiny issue. Version number didn't get bumped in 2.6.3. Still reports as 2.6.2.

**Comment by qphoria** [comment]
Yea.. the vqmod code didn't change, therefore is still 2.6.2. Only the OpenCart vqmod_opencart.xml file changed which isn't being versioned separately so it is confusing. I guess we could have done 2.6.2.1 or something. Ah well.
