### ISSUE TITLE
vQmod (Opencart): When using replace with offset empty lines are retained

### ISSUE THREAD

**Issue by kanenas** [vqmod/vqmod#114]
**vQmod**: v.2.6.2
**Opencart**: v.2.3.0.2

When using:
```
<operation error="skip">
  <search position="replace" offset="10"><![CDATA[<?php //Find this ?>]]></search>
  <add><![CDATA[<?php //Replace it with this ?>]]></add>
</operation>
```
Although everything works just fine, 9 empty lines are retained.

Is this standard behavior or it is something wrong with my installation?

**Comment by JAY6390** [comment]
This is standard behaviour and how the system is meant to work
