### ISSUE TITLE
Ampersand in operation info attribute breaks the overwrite

### ISSUE THREAD

**Issue by jeesus** [vqmod/vqmod#119]
I noticed that my overwrite isn't working at all for a specific operation and at some point figured that without ampersand character (&) in the info attribute the overwrite would work. Haven't checked for other special characters to see if the problem is wider.

Doesn't work:
`<operation info="Replace date & time info with selection of timetable events">`
Works:
`<operation info="Replace date and time info with selection of timetable events">`

vQmod 2.6.3
OpenCart 3.0.2.0

**Comment by JAY6390** [comment]
That's how XML works, and isn't a bug with VQMod. You need to use the escape &amp; instead if you want to put that in there
