### ISSUE TITLE
vqmod-2.4.1-opencart + Opencart 2.0.0.0 does not start

### ISSUE THREAD

**Issue by ghost** [vqmod/vqmod#12]
Installed Opencart 2.0.0.0 + vqmod but cannot run:
![2014-11-12 18_29_40-apache2 ubuntu default page_ it works](https://cloud.githubusercontent.com/assets/1749642/5009082/1bcfb64c-6a9e-11e4-8b1c-ed91f81271eb.png)
![2014-11-12 18_29_55-404 not found](https://cloud.githubusercontent.com/assets/1749642/5009086/25065040-6a9e-11e4-8fa2-da2c667335f1.png)
![2014-11-12 18_26_07-ubuntu ip-172-30-1-101_ _var_www](https://cloud.githubusercontent.com/assets/1749642/5009088/2eaf3634-6a9e-11e4-90ce-300c31f73929.png)
![2014-11-12 18_26_46-postimage org - free image hosting _ image upload](https://cloud.githubusercontent.com/assets/1749642/5009094/3404c072-6a9e-11e4-9c51-bf5441361a93.png)

**Comment by yousaf123456** [comment]
Can you please guide me regarding this issue, as I am facing same problem.

Thanks.

**Comment by qphoria** [comment]
This was already solved.. if you have the same issue, you have the same solution.
