### ISSUE TITLE
VQMOD error message help!

### ISSUE THREAD

**Issue by sjuniorbrown** [vqmod/vqmod#120]
Can anyone help me with this problem. I don't understand Vqmod well enough to crack this,any help will be greatly appreciated.

`Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model extension/module/ocseo_plus!' in /var/www/vhosts/74/664182/webspace/httpdocs/mumsandbabies/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php:59 Stack trace: #0 /var/www/vhosts/74/664182/webspace/httpdocs/mumsandbabies/system/ocmodify/engine/loader.php(100): Loader->model('extension/modul...') #1 /var/www/vhosts/74/664182/webspace/httpdocs/mumsandbabies/system/storage/modification/admin/controller/catalog/product.php(1036): OCMLoader->model('extension/modul...') #2 /var/www/vhosts/74/664182/webspace/httpdocs/mumsandbabies/system/storage/modification/admin/controller/catalog/product.php(116): ControllerCatalogProduct->getForm() #3 [internal function]: ControllerCatalogProduct->edit() #4 /var/www/vhosts/74/664182/webspace/httpdocs/mumsandbabies/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(66): call_user_func_array(Array, Array) #5 /var/www/vhosts/74/664182/webspace/httpdocs/mumsandbabies/admin/ in /var/www/vhosts/74/664182/webspace/httpdocs/mumsandbabies/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 59`

**Comment by JAY6390** [comment]
Not an issue with VQMod as such - its an issue with your "seo plus" extension and you need to contact them
