### ISSUE TITLE
OpenCart caching vQmod - issue or not?

### ISSUE THREAD

**Issue by jeesus** [vqmod/vqmod#121]
So i've been having problems modifing the files with vQmod. At some point changes to certain files are not taking effect. Even if I clear vqcache folder and `checked.cache` and `mods.cache` files. 

Let's assume I have following modification:
`<file path="admin/view/template/catalog/product_form.twig">
/* bunch of code */
</file>`

All other file paths modified in the same XML file are working properly. In order for changes in this file to take effect, I'd have to delete OpenCart's `/storage/cache` folder. Is this intended behavior? Changes made to that mentioned filepath reflect in vqcache folder, but not in browser until OC cache is deleted.

I'm not using vQmod alongside with OCmod.

vQmod 2.6.3
OpenCart 3.0.2.0

**Comment by qphoria** [comment]
Yes opencart Twig template system has its own cache system. You can clear it using the hidden "gear" icon on the main admin dashboard. Not sure why it is so hidden but click that to clear the template cache or disable it while making vqmod changes..

**Comment by jeesus** [comment]
Thanks! Indeed I hadn't noticed that gear icon and after seeing it seems obvious why things are the way they are.

**Comment by ar27111994** [comment]
Hi, I'm having the same issue while creating a **vqmod** for editing **order notification/alert for admin**. I've already tried the Dashboard Gear Solution, but it didn't work. And also, the **`order_alert.twig`** file had repeating lines of text that I added in the vqmod file. It seems that the edited text was added to the vqcache file as many times as I refreshed the modifications cache in the admin panel, but all of that is useless as the final admin order email still has the old template 👎 Anyhow after that I tried the Dashboard Gear Solution and cleared the theme cache and even disabled it but none of that worked. After that, I deleted all the **`vqcache`** files but now even the vqcache files from the **`order alert vqmod`** aren't appearing. Please help. My vqmod version is `2.6.3` and all other vqmods (all created by me) are working fine. There is no **error/conflict** in **vqmod logs** or the **opencart error log**.
