### ISSUE TITLE
vqmod opencart works perfectly locally but does not work remotely.

### ISSUE THREAD

**Issue by alexantosh** [vqmod/vqmod#123]
Hi all, I just transferred a site that works ok locally on my machine but vqmode scripts don't seem to run remotely. I have changed all folder permissions to 777 and also changed the 
$stripped_filename = preg_replace('~^' . preg_quote(self::getCwd(), '~i') . '~i', '', $sourcePath);

line but in vain. so what should i try next? Thank you all.

**Comment by JAY6390** [comment]
What are the differences between the two systems? Are they both linux/windows? Are the files mods.cache and checked.cache being generated? Also, have you checked your php logs for any clues?

**Comment by alexantosh** [comment]
Remote server is running on linux but locally i was running xampp on windows.
I have the checked.cache(last modified: today) but the mods,cache(was last modified before i uploaded the site.) I checked the logs folder but it was last modified before i uploaded the files on the system.
None of the .log files has been modified since last update to server.

**Comment by JAY6390** [comment]
Personally I would rename the vqmod folder to vqmod2, then upload a clean version, and see if files are generated. If they are, transfer the .xml files from vqmod2 to the vqmod1 dir.

**Comment by alexantosh** [comment]
ok, thanks. let me try that right now.

**Comment by alexantosh** [comment]
Hey thanks alot. I dont know what happened, but just changing the name and putting a fresh vqmod solved it all. now the last modified dates align as well. but I dont know why this happened. do you have any idea?

**Comment by JAY6390** [comment]
Best guess, one or more of the files weren't writeable properly, and just needed changing to the right permissions, but honestly can't say for sure. The main thing is it works now :)

**Comment by alexantosh** [comment]
indeed :)
