### ISSUE TITLE
oc 3 add extra custom field for product option using vqmod

### ISSUE THREAD

**Issue by alexantosh** [vqmod/vqmod#124]
hi, am not sure whether to post this issue in OC forums or here. But if you can help i will appreciate it. if not, i will move it to OC but will appreciate anyway. I want to add a custom option field for a product. this will be a downloadable file (text file, image or pdf). I wana do this with vqmod. I have gone through the scripting post and examples, but I dont think i can handle this with just that data. If you can guide me on how to proceed or examples that do the same, I will appreciate it. There's post that pretty much achieves the same thing for OC 1.4 version but that doent apply here as structures and approach change and they dont use vqmode. they modify the core files, which  i want to avoid at all costs. thanks. But if i have to go to the core files, I dont mind doing that either. Thanks in advance

**Comment by JAY6390** [comment]
Hi

This is for VQMod engine related issues, not general OpenCart help. You'll need to move this to the OC forums as you've suggested. As for examples to do what you want, its unlikely someone is going to offer these as it'll essentially involve them coding the whole thing for you

Kind regards
Jay

**Comment by alexantosh** [comment]
ok, explaining it this way makes sense. first i need to know exactly what to do and what files to modify. thanks.
