### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by BorisGorskiy** [vqmod/vqmod#125]
Hi!
Have installed the module according to the instructions, but then, when entering the website, the error message: Fatal error: Uncaught Error: Class 'VQMod' not found in /home/users/b/bag/domains/maxtechno.ru/index.php:10 Stack trace: #0 {main} thrown in /home/users/b/bag/domains/maxtechno.ru/index.php on line 10

What's wrong?

**Comment by qphoria** [comment]
Sounds like you didn't upload the vqmod files . Is everything uploaded?

**Comment by BorisGorskiy** [comment]
Yes. I was told that VQMOD do not install on OpenCart 2. He works for OCMOD. Your module works on OCMOD ?

**Comment by BorisGorskiy** [comment]
Russin version

**Comment by qphoria** [comment]
That is incorrect. vQmod works on all versions of OpenCart. please contact me here with ftp details and I'll take a look and install for you. https://opencartguru.com/index.php?route=information/contact
