### ISSUE TITLE
.twig file not modified also the corresponding cache file not formed

### ISSUE THREAD

**Issue by alexantosh** [vqmod/vqmod#127]
Hello, I have a peculiar situation here. I got a vqmod whose sections are working fine except the part that makes changes to OC 3's product.twig file. Changes i make to this file are not reflected whatsoever and I checked the vqcache, all other modified files have corresponding cached files - including product_form.twig, which is even more confusing. I have tried clearing ALL the cache but no solution and absolutely nothing in the vqmod error logs. So what could be causing this. All other modifications are working fine. It's my first vqmod but am already in love with it. very easy manipulation of multiple files. 
Thanks for all the suggestions and tips in advance.

**Comment by kanenas** [comment]
@alexantosh have you checked this https://github.com/vqmod/vqmod/issues/121?

**Comment by alexantosh** [comment]
@kanenas yes i did. but as i mentioned. None of the things mentioned there help. clearing all caches, .... 
At least they had the modified file show up in vqcache, I personally don't even see the corresponding file modified. Althougj i see changes i made to another twig file being reflected and they are working properly in the same document. 
vq2-admin_view_template_catalog_product_form.twig -> this one shows up fine, no problem.
vq2-catalog_view_theme_default_template_product_product.twig -> i expected to see something like this at least. but that also does not exist. Plus no changes on front end.

**Comment by ar27111994** [comment]
Hi, I'm having the same issue while creating a **vqmod** for editing **order notification/alert for admin**. I've already tried the Dashboard Gear Solution, but it didn't work. And also, the **`order_alert.twig`** file had repeating lines of text that I added in the vqmod file. It seems that the edited text was added to the vqcache file as many times as I refreshed the modifications cache in the admin panel, but all of that is useless as the final admin order email still has the old template 👎 Anyhow after that I tried the Dashboard Gear Solution and cleared the theme cache and even disabled it but none of that worked. After that, I deleted all the **`vqcache`** files but now even the vqcache files from the **`order alert vqmod`** aren't appearing. Please help. My vqmod version is `2.6.3` and all other vqmods (all created by me) are working fine. There is no **error/conflict** in **vqmod logs** or the **opencart error log**.

**Comment by ar27111994** [comment]
Ok, Somehow it worked after deleting VQMod's vqcache files, checked and mods cache files. And yes there were some errors too but logical not syntactical.

**Comment by JAY6390** [comment]
#134
