### ISSUE TITLE
Issue Opencart 3 

### ISSUE THREAD

**Issue by florianace** [vqmod/vqmod#129]
if( ! class_exists( 'VQMod' ) ) { class VQMod { public static $_vqversion = '2.6.1'; public static $_virtualMFP = true; public static $directorySeparator = ''; public static function modCheck( $path ) { return $path; } } }

I tried to upgrade, to clear cache, to reinstall vqmod, I even did install the backup I have. I couldn't solve this on my own. 
Please help!

**Comment by JAY6390** [comment]
I don't actually see a question. What is it you're having an issue with? Also, you should be using version 2.6.3 for OpenCart 3

**Comment by florianace** [comment]
I did upgrade to 2.6.3 and I still get this in my header. And my website doesn't launches like it should.

**Comment by florianace** [comment]
www.atv.kawamotors.ro

**Comment by JAY6390** [comment]
Does your /vqmod/vqmod.php file have a `<?php` at the start of it? That's the only reason I can think of that this would happen, and I can't reproduce the same thing

**Comment by florianace** [comment]
yes, it does

**Comment by JAY6390** [comment]
Really not sure then to be honest. VQMods include has worked the same for years. The only other thing I can think of is to check with your host to see if they do anything peculiar with includes in php

**Comment by florianace** [comment]
I will reinstall everything..
