### ISSUE TITLE
Suggestion: warn/don't generate mods.cache if installer has not been run

### ISSUE THREAD

**Issue by scottcwilson** [vqmod/vqmod#130]
I copied the vqmod files to my site and saw that the mods.cache file was being created ... but since I hadn't run the vqmod installer, none of my changes were actually inserted into the core files being changed!  As a suggestion to help rookies, could you detect and flag this condition (or at least not generate the mods.cache file?)

**Comment by qphoria** [comment]
That's not possible. mods.cache gets generated when the vqmod file is included and the function to check mods was called. If vqmod wasn't installed. those functions would never be called and mods.cache simply could not be generated. My guess is you possibly had it installed before and mods.cache was left over or you had it installed on either the catalog OR admin index files but not both so it was partially functional.

**Comment by scottcwilson** [comment]
Yes, I'm pretty sure there was some cruft lying around that made this extra confusing.  OK, thanks for the response anyway.  Closing.
