### ISSUE TITLE
[Bug] iafter replacing inline vs adding after inline

### ISSUE THREAD

**Issue by MrPlow254** [vqmod/vqmod#136]
iafter is not functioning properly. It is deleting the search and will insert the code after the search inline.

```
<file path="catalog/model/catalog/product.php">
<operation>
	<search position="iafter"><![CDATA[$sql = "SELECT p.product_id,]]></search>
	<add><![CDATA[cp.category_id,]]></add>
</operation>
</file>
```

**Comment by JAY6390** [comment]
What version of vqmod are you using? I after works just fine for me in every version since it was implemented

**Comment by MrPlow254** [comment]
Sorry, I it am using OCMOD apparently.
