### ISSUE TITLE
[Error] Index code reference is incorrect

### ISSUE THREAD

**Issue by MrPlow254** [vqmod/vqmod#137]
"
If the search string is "echo" and there are 5 echos in the file, but only want to replace the 1st and 3rd, use index="1,3"
"
If you use index="1" it will replace/insert whatever index 2. To replace index 1 I have to use index="0"

**Comment by JAY6390** [comment]
Same question here. What version are you using?

**Comment by MrPlow254** [comment]
latest build of opencart. I would assume this is the latest version of vqmod. Would this be a bug only related to opencart?

**Comment by MrPlow254** [comment]
hmmm, i just did a quick search through opencart. He has a custom version of the index. So yours works.
