### ISSUE TITLE
clone

### ISSUE THREAD

**Issue by austurki** [vqmod/vqmod#138]
hi
how are you today
i install the extention but unfortunatly i think still not installing well
becausewhen i try to clone my website...all files will be cloned except your extention folder mus upload it manully
what can i do?

**Comment by JAY6390** [comment]
Whatever it is is server related and not to do with vqmod

**Comment by austurki** [comment]
aha
it not (writable (either 755 or 777). issue?
because this make some problem in website when i change it

**Comment by JAY6390** [comment]
Again server issue not vqmod. We offer installations for a fee of $20 if you wish for us to install. Otherwise you will need to contact a developer
