### ISSUE TITLE
Cache files generated in the root of the site

### ISSUE THREAD

**Issue by hypemedia** [vqmod/vqmod#142]
The vqmod cache files are generated in the root of the site, not on the /vqmod/vqcache folder.

It is Opencart 3.
Any ideas on what it can be?

**Comment by JAY6390** [comment]
Can you show your file structure? And do you have your system directory outside of the document root?

**Comment by hypemedia** [comment]
Dou you need access to FTP?

No I have the system directory inside the root of the site.

Daniel
Hype Media

Telefon: +40 314 370 179
Mobil: +40 724 888 304

Bd. Eroii Sanitari Nr. 9, Et.1, ap.2, 
Sector 5, 050471 - Bucuresti
www.hype.ro

**Comment by JAY6390** [comment]
Just a screenshot would do. As this is the only instance we've seen of this, its likely an issue with your configuration

**Comment by hypemedia** [comment]
I will try to reinstall vqmod and see if the error still occurs.

Hype Media

Telefon: +40 314 370 179
Mobil: +40 724 888 304

Bd. Eroii Sanitari Nr. 9, Et.1, ap.2, 
Sector 5, 050471 - Bucuresti
www.hype.ro

**Comment by hypemedia** [comment]
After installing the latest version of vqmod the problem is gone I forgot to say that it was version 2.6.2 after installing 2.6.3 the problem is gone.


Hype Media

Telefon: +40 314 370 179
Mobil: +40 724 888 304

Bd. Eroii Sanitari Nr. 9, Et.1, ap.2, 
Sector 5, 050471 - Bucuresti
www.hype.ro

**Comment by JAY6390** [comment]
Great. Glad it's resolved
