### ISSUE TITLE
LOSS OF DATA!! - Too Many Option Values

### ISSUE THREAD

**Issue by MarbleMark** [vqmod/vqmod#144]
At first I thought this was caused by more than 64 option values in a list, but then I couldn't reproduce it in some circumstances (maybe I wasn't counting correctly?), but now I can reproduce it every time by creating a product with 4 options, one of which had more than 64 values.   I don't think the other three options matter, but the data corruption can change any of the option values, or anything else in the product (name, price, SEO, SKU, metatags, etc.)

When I save the product in the Admin version it produces a message similar to the one below.  However, it corrupts the data, too!  The message is slightly different depending on which fields are being corrupted.

The options are all Select types, if it matters.

Notice: Undefined index: product_seo_url in /home/.../vqmod/vqcache/vq2-storage_modification_admin_controller_catalog_product.php on line 1281
Notice: Undefined index: points in /home/.../storage/modification/admin/model/catalog/product.php on line 194
Notice: Undefined index: priority in /home/.../storage/modification/admin/model/catalog/product.php on line 289
Notice: Undefined index: price in /home/.../storage/modification/admin/model/catalog/product.php on line 289
Notice: Undefined index: date_start in /home/.../storage/modification/admin/model/catalog/product.php on line 289
Notice: Undefined index: date_end in /home/.../storage/modification/admin/model/catalog/product.php on line 289
Warning: Cannot modify header information - headers already sent by (output started at /home/.../admin/controller/startup/error.php:34) in /home/.../system/library/response.php on line 36

**Comment by qphoria** [comment]
Not sure why this is being posted here. Limits are based on your server
settings for post_max_data and will occur even if you aren't using vqmod.
It's because of 64 options which is pretty obscene, but it all depends on
what your server is set to handle. Think of all the individual fields that
need to be posted back to the server when saving. Ask your host to increase
the post_max_data value and that should fix it.

**Comment by MarbleMark** [comment]
Sorry, I posted it here because the first error referenced vqmod, and that was the last thing I installed.

64 options isn't obscene when I live in a state with 87 counties from which to choose.

I'll contact my web host.

Thanks,

Mark
