### ISSUE TITLE
Warn users about having DIR_STORAGE outside webroot

### ISSUE THREAD

**Issue by james090500** [vqmod/vqmod#145]
I recently encountered an issue with my opencart system acting EXTREMELY slow. Sometimes timing out and sometimes taking 10-20 seconds to load the homepage. 

This was due to the webroot/vqmod/checked.cache file reaching around 200MB as it has repeated lines of /home/private_webroot/vendor/autoload.php as opencart told me to move the storage folder outside of my main webroot.

Upon deleting the checked.cache and moving /home/private_webroot/ to /home/webroot/storage and locking down the directory from outside access instantly improved my sites performance and no more duped lines in the checked.cache.

Some documentation about this would be nice as it took me ages to figure out the issue. 

Or even a fix to avoid duped lines in checked.cache.

**Comment by gdegraaf** [comment]
@james090500 how did you lock down the directory from outside access?

**Comment by JAY6390** [comment]
See #135

**Comment by james090500** [comment]
> @james090500 how did you lock down the directory from outside access?

Adjust chmod correctly and added a .htaccess deny from all for extra measure,



> See #135

Might be nice to have a warning added to the Readme/installation instructions though?
