### ISSUE TITLE
"vqmod.php on line 684" - 

### ISSUE THREAD

**Issue by trueliarx** [vqmod/vqmod#147]
Several websites have this error with (probably) php 7.2 and the latest version of vqmod

 Warning: "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? in */vqmod/vqmod.php on line 684

https://www.google.com/search?q="vqmod.php+on+line+684"

I *fixed* it with a "break 2" as suggested by the warning.

**Comment by timint** [comment]
break 2 is going to execute the last two lines in the foreach loop line 761:

```
			ksort($tmp);
			$tmp = $this->_implodeData($tmp);
```
continue 3 is going to skip them.

**Comment by aris9ian** [comment]
https://wiki.php.net/rfc/continue_on_switch_deprecation

You can replace **continue** with **break** as per php's wiki!

**Comment by faca5** [comment]
Hello.

I got this error on PHP 7.3. On PHP 7.1 works.

Do you have any update?

Thank you.

**Comment by aris9ian** [comment]
@faca5 

On PHP 7.3 you need to replace "continue" statements with "break" when you're inside a "switch".

In this case on line 684 replace "continue" with "break", but it is very possible to receive similar errors in the future in another line. I suggest you replace all "continue" statements (only those inside a switch structure) in the vqmod.php file.

**Comment by faca5** [comment]
Hello.
Excellent. It works. Thank you very much.

**Comment by sixty9fordkiller** [comment]
[In this case on line 684 replace "continue" with "break"] 

^^^Worked for me. Thank you very much

**Comment by JAY6390** [comment]
Fixed in latest release

**Comment by LybaNL** [comment]
All updates aside the issue seem to persist. If the break is commented or replaced nothing seems to have any effect. Any suggestions?
