### ISSUE TITLE
Wrong version number?

### ISSUE THREAD

**Issue by jfcardinal** [vqmod/vqmod#148]
I downloaded https://github.com/vqmod/vqmod/releases/tag/v2.6.3-opencart

I opened vqmod/vqmod.php, and I see this at line 7 (minus some spacing):

public static $_vqversion = '2.6.2'; // Current version number

I'd expect to see '2.6.3'.

EDIT: Forgot to include link

**Comment by JAY6390** [comment]
Yeah I mentioned the same thing to Q when he released it. Technically both the same but I think the vqmod had varied or something. @qphoria what was the reason again?
