### ISSUE TITLE
[Feature Request] Support for <Addfile> tag

### ISSUE THREAD

**Issue by Bossman1337** [vqmod/vqmod#149]
Support for a `<Addfile>` tag. 

Example: `<Addfile position="replace">example_inject.php</Addfile>`

As long as the file is within the root of the zip (xxxx.ocmod.zip/xxxx.vqmod.zip) file it will use it.

The benefit would be better for editing and using syntax highlighting within your editing programme. For example when adding PHP code. Rather than editing within the XML file that won't highlight the PHP syntax.

When processing the file it could just remove the `<?php` tag at the start and if present the ending `?>` tag or just replace them with the CDATA tags. in effect being the same as the `<Add>` tag.

What do you think?

**Comment by JAY6390** [comment]
Really not 100% sure what you're suggesting here - Are you saying split code out of the xml file into component files?

Kind regards
Jay

**Comment by Bossman1337** [comment]
Hi Jay,

Yes, the sole purpose would be for editing, if I have a php function that is quite large that I want to insert for example, then managing/editing that php code in xml doesn’t show any php syntax highlighting.

If that makes sense?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JAY6390** [comment]
It does, but I think that's a rather convoluted solution just to show pretty code in the editor.. Instead of a single file for your vqmod edits you could potentially have hundreds of files. Also, on occasion you would want to keep the PHP tags so can't see a logical way of doing that

**Comment by Bossman1337** [comment]
Yeah, like I say just throwing an idea in the air, it would be nice to have the option, there will be ways to achieve the php tag replacement and keeping ones you need etc..

I like pretty code ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Bossman1337** [comment]
Maybe a plug-in for sublime would be a better option, might have a look into that..

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
