### ISSUE TITLE
_getMods function causing performance issues

### ISSUE THREAD

**Issue by gdegraaf** [vqmod/vqmod#150]
I was experiencing performance issues on my website. About every 1 to 2 weeks the site got so slow that the server memory could not handle it any more. I already found out that clearing the vqmod cache (files in cache folder + mods.cache and checked.cache) immediately solved this problem but I could not found any more information about the issue.

So I installed New Relic APM to see if I could get the deeper cause of the issue. It looks like the _getMods function is causing the issue. Does anyone have any idea how this can be prevented other than clearing the cache weekly?

Any other people experiencing this issue with OC 3.0.2.0 with default theme?

![Screenshot 2019-03-12 at 12 44 26](https://user-images.githubusercontent.com/1894150/54197591-9d02dc80-44c4-11e9-8fcc-c0486e69a14d.png)

**Comment by JAY6390** [comment]
The only performance problem we've seen has been when people move the system directory outside of the root directory. See #135
