### ISSUE TITLE
vqmod crashing my site

### ISSUE THREAD

**Issue by dspurlock** [vqmod/vqmod#153]
About a year ago I installed vqmod on my opencart 3.0.2.0 site. Everything worked fine. about 4 months ago one day just out of nowhere I started getting error message. In trying to isolate the problem I disabled vqmod and my site returned to normal. So I uninstalled it.

Today I wanted to install and extension which required vqmod. So I reinstalled vqmod, not the extension. As after installing, when I started changing the permissions It crashed my site and I get this error message "Sorry, that didn’t work. Please try again or come back later. 500 Error. Internal Server Error." when I try to access the front end. The admin side of the site still works. I changed the permissions on the index.php in the root director from 644 to 666. I also changed the others as shown in you installation video with the same result.

Can you please advise what might be causing this problem?

Thanks in advance for any assistance.
Dan

**Comment by JAY6390** [comment]
There's no clear answer for that Dan. It could be a multitude of things, but almost certainly an issue with configuration on the server. VQMod wouldnt break for no reason. I do offer an install service for $20. If you'd like me to do so, contact me using support [at] djgweb [dot] co [dot] uk

Kind regards
Jay
