### ISSUE TITLE
[feature] module dependancy

### ISSUE THREAD

**Issue by QualityWorks** [vqmod/vqmod#158]
Today we had an error because a module was not installed through the extensions > module list, but the vqmod that came with it, was installed. A database change had not been made and an error was thrown.
This made me think of this feature;
add a `<module></module>` in the main part of the vqmod file
example:
`<module>extension/module/module_this_came_with.php</module>`
then the feature would be that vqmod checks id the module is active, if not, it doesn't apply the changes.
If there is no corresponding module, leave the tag blank and it will always apply the mod.
This should keep the code a lot cleaner for modules that are inactive / unused.

**Comment by qphoria** [comment]
While vQmod is mostly used on opencart, it was designed to be platform agnostic to be used generically with other platforms. Litecart and a few other platforms have attempted integration in the past. So there is intentionally nothing specific to opencart or any other platform,l. It wouldn't make sense add this. 

Better to just fix the bug in the user 😎

**Comment by QualityWorks** [comment]
I see what you're saying and it makes sense. I'm not sure my issue is a bug though. Install the module and the error is gone. But it did make me think about changes that are made by vqmod for modules that are inactive. Even if they have been installed and don't cause errors, why would we add the code changes if the module itself isn't used.
