### ISSUE TITLE
[Feature Request] Multiline Search

### ISSUE THREAD

**Issue by timint** [vqmod/vqmod#16]
I would like to push for a discussion of multiline search support.
Here is something I came up with that could be useful for starters:

```
function preg_replacement_quote($string) {
  return preg_replace('#(\$|\\\\)(?=\d)#', '\\\\\1', $string);
}

function modify_string($haystack, $search, $insert, $operation) {

  $search_regexp = preg_split("#\R+#", trim($search)); // Convert multiple lines to array
  foreach(array_keys($search_regexp) as $key) {
    $search_regexp[$key] = preg_quote(trim($search_regexp[$key]), '#'); // Turn line into regular expression
  }
  $search_regexp = "#(\\s+?" . implode('\\s+', $search_regexp) . "\\s+?)#"; // Glue

  switch($operation) {
    case 'prepend':
      return preg_replace($search_regexp, '$1' . $insert, $haystack);
    case 'replace':
      return preg_replace($search_regexp, $insert, $haystack);
    case 'append':
      return preg_replace($search_regexp, preg_replacement_quote($insert) . '$1', $haystack);
    default:
      trigger_error("Unknown operation ($operation)", E_USER_ERROR);
  }
}
```

The code should not be used for production. I had some troubles escaping $insert where PHP replaced both $1 and \1 with the first matched pair.

**Comment by JAY6390** [comment]
Hi Tim

Thanks for the feedback. We've discussed the multiline issue a few times privately and have already worked out a way that it could be implemented. However, with the OCMod integration into OpenCart we'd decided to hold back and see what was going on with it and if it was worth actively pursuing VQMod's feature enhancements.

On a tangent, I see you're the developer of LiteCart. I took a look a while ago and was really impressed with it and see you integrated VQMod into the core which is great. If I recall correctly you weren't using MVC at the time (around summer last year) for LiteCart which put me off using it and developing extensions for it to be honest. Hopefully this isn't still the case with your new release? I'll have to download and check at some point when I get a moment

Kind regards
Jay

**Comment by timint** [comment]
Hi Jay, thanks for getting back to me on the topic.

It's with a happy smile I read LiteCart caught your impression. :) It's some hard work I must say. Since version 1.2+ I have separated logic from HTML in and also introduced vQMod. I was thinking of writing my own modification system, but why invent the wheel again when Qphoria kindly granted permission to use vQmod in LiteCart. I wouldn't say LiteCart is a pure MVC framework, as I tried to move away from the disadvantages in MVC in the way OpenCart does it. This is where simplicity and convenience have a lot of impact on the work. I think the separation of logic in 1.2+ is one big benefit for template makers. I think the strongest thing in LiteCart is the plug 'n play hook inspired system model and the reduced amount of code compared to the other platforms. Do let me know whenever you decide to try it out again sometime.

As for the topic, I'm looking forward to see what awaits the development of vQmod and possible future multiline support.

**Comment by EveryAuction** [comment]
@JAY6390 , thank Aou for mentioning LiteCart, it could just about be, what I was looking for, to avoid the Need of a OC-type Truck, if a Job can be done with a small Daihatsu as well.
Ernie
bigmax.ch/lc/

**Comment by timint** [comment]
@JAY6390: Any news on the OCMod scene and the future of vQmod?

**Comment by susanlummis** [comment]
I am back in the office on Wed 3rd June, for urgent things please contact Thomas or Steve.

**Comment by JAY6390** [comment]
@timint Still waiting to see how OCMod moves in the next release really. The 2.0.3.0 version isn't really an update to OpenCart, just more bloatware/money making affiliations and a few bug fixes. It seems people are still using VQMod over OCMod though by the majority of the big developers at least, so the future of VQMod looks promising to be supported/updated and may rewrite it for a 3.0 release at some point with multiline being the biggest but not the only feature implemented

**Comment by timint** [comment]
I wasn't too found of vQmod in the beginning due to the XML syntax, but it's a way of getting used to it. It almost has unlimited potential compared to hooks/events. I would love to share my thoughts and ideas for a potential 3.0. Basically I think it could be even lighter than it is today and also use PHP's native error handler trigger_error() instead of it's own.

**Comment by JAY6390** [comment]
Hi Tim

More than happy to hear ideas for improvements. Feel free to e-mail me jay [at] jaygilford [dot] com

Kind regards
Jay
