### ISSUE TITLE
Wiki issues

### ISSUE THREAD

**Issue by likemusic** [vqmod/vqmod#160]
Wiki pages has some misprints in their markdown.

How to create pull-request to them or push fixes?

By the way, why so many html-tags used in wiki-pages, when markdown has equivalents for this?

**Comment by qphoria** [comment]
2 reasons. 
1. Markdown is trash. Wikis should have used bbcode from the start. We didn't need another garbage, unintuitive alternative. 
2. Before we moved to wiki we had this all hosted on another site so we just copied it all over

**Comment by qphoria** [comment]
> By the way, why so many html-tags used in wiki-pages, when markdown has equivalents for this?

It was originally posted on a website...then we converted it to just use git wiki
