### ISSUE TITLE
Using Vqmod in new symfony project

### ISSUE THREAD

**Issue by hiniestic** [vqmod/vqmod#161]
I have used this function on the pased in Opencart working great. Now I want to use it in a new Symfony project. This uses composer, so, as described in the Wiki, I have changed my index.php __DIR__.'/vendor/autoload.php' to this:

`require_once __DIR__.'/vqmod/vqmod.php';
VQMod::bootup();

require_once VQMod::modCheck(__DIR__.'/vendor/autoload.php');`

but it is not working. Is there anything I have misunderstood?

**Comment by JAY6390** [comment]
You would need to make a vqmod to also parse any autoloads too, just as OpenCarts does
