### ISSUE TITLE
Opencart Vq Mode Checked.cache file - definitely solved

### ISSUE THREAD

**Issue by e-ticaretuzman** [vqmod/vqmod#162]
Use cron command on cpanel or plesk panel. Automatically delete at certain time intervals.

create: a file save; clear.php
write to file:

```
<?php
unlink("../public_html/vqmod/checked.cache");
echo "vqMod Cache File checked.cache deleted successfully.";
?>
```
Cpanel & Plesk Panels
Set it, Cron Time Command:
php -q /home/yourfolderway/public_html/clear.php
Set :
*/5 * * * *
e-ticaretuzman

Türkçe Çözüm :
cpanel yada plesk panel üzerinde cron komutu kullanın. Belirli zaman aralıkları ile otomatik silsin.

oluşturun: clear.php
dosyaya yazın :

```
<?php
unlink("../public_html/vqmod/checked.cache");
echo "vqMod Cache Dosyası checked.cache başarıyla silindi.";
?>
```
Cpanel & Plesk Panelden
Ayarlayın, Cron Zamanlı Komut :
php -q /home/yourfolderway/public_html/clear.php
Ayarlayın :
*/5 * * * *

e-ticaretuzman

**Comment by JAY6390** [comment]
Closed - see https://github.com/vqmod/vqmod/issues/135#issuecomment-864124704
