### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Julmuzy** [vqmod/vqmod#166]
vQmod version:2.6.0

Getting this message in the server log:
"mod_fcgid: stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 33554440 bytes) in /var/www/vhosts/shopsite.blah/httpdocs/eshop/vqmod/vqmod.php on line 336"

It just started happening for no apparent reason. No changes made to anything and I googled it and really didn't get a worthwhile solution. Various line numbers are recorded all with the same error. User sees the site and can select a category but when loading a new route the screen goes blank because the server is experiencing a memory issue as defined by the error logs. No vQmod error log.

Do you think this is a vqmod issue or is it a server configuration problem somewhere?

As always any helpful advice would be appreciated.

**Comment by qphoria** [comment]
Upgrade to the latest
