### ISSUE TITLE
Add XML Schema XSD file

### ISSUE THREAD

**Issue by Gamesh** [vqmod/vqmod#17]
Not only it allows validating the XML in IDE like Netbeans and similar, but it also supplies autocomplete functionality witch is very useful.
![attribute-values-autocomplete](https://cloud.githubusercontent.com/assets/171747/5696213/89cfb0ca-99ce-11e4-84ae-31fb927d2ff2.png)
![tags-autocomplete](https://cloud.githubusercontent.com/assets/171747/5696214/89e92cc6-99ce-11e4-9b1a-ba76fd225596.png)
Ofcourse xml files would need to be namespaced and linked to xsd for this to work.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<modification 
    xmlns="https://github.com/vqmod/vqmod"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/vqmod/vqmod https://raw.github.com/vqmod/vqmod/vqmod.xsd">
</modification>
```

I'm currently working on a XSD file for vqmod. would you consider adding it into repository if i would send a pull request?

**Comment by JAY6390** [comment]
Sure I don't see why not
