### ISSUE TITLE
vqmod/install missing index.php

### ISSUE THREAD

**Issue by alw1746** [vqmod/vqmod#170]
vqmod v2.6.7 issue.

When I browse to opencart/vqmod/install, a directory listing is shown instead of the expected success message. I copied index.php from v2.6.6 and that worked, hope this workaround is ok ie no change in the latest version(2.6.7).

**Comment by qphoria** [comment]
Please read the front page. The files have been changed now to put opencart script files into its own repo

**Comment by alw1746** [comment]
Thanks! I can see now vqmod.com has a good explanation of everything. I'll suggest to opencart their installation page should be using this link for greater details.
    On Sunday, 10 July 2022 at 11:12:08 pm AEST, qphoria ***@***.***> wrote:  
 
 


Please read the front page. The files have been changed now to put opencart script files into its own repo
