### ISSUE TITLE
Deprecated: Use of "self" in callables is deprecated

### ISSUE THREAD

**Issue by timint** [vqmod/vqmod#172]
This line gives a deprecated error in php 8.2.
https://github.com/vqmod/vqmod/blob/fe912c64bac41b156b67b95bf2d8a6e905d2b22f/vqmod/vqmod.php#L431

> Deprecated: Use of "self" in callables is deprecated

Here is the fix:

`              $part = preg_replace_callback('#[^*]+#', [self::class, '_quotePath'], $part);`

Reference: https://php.watch/versions/8.2/partially-supported-callable-deprecation

**Comment by osworx** [comment]
Any process on this?
More and more providers are switching to php 8.2 - tired of doing it myself.

**Comment by JAY6390** [comment]
@osworx Do you have a solution to this? I'm not sure how to do this, so if you want to make a pull request we can add it to the next release

**Comment by timint** [comment]
Is no one reading the initial post?

`  $part = preg_replace_callback('#[^*]+#', [self::class, '_quotePath'], $part);`

**Comment by JAY6390** [comment]
Apologies @timint . I didn't see the rest of this thread, I just saw the last reply. Thanks for providing the fix. I'll implement this if Q doesn't and get a release out in the next couple of days

**Comment by osworx** [comment]
> Is no one reading the initial post?
> 
> ` $part = preg_replace_callback('#[^*]+#', [self::class, '_quotePath'], $part);`

Of ccourse, but with that it deos NOT work with php 8.2

**Comment by JAY6390** [comment]
@osworx @timint If what I'm understanding correctly, Tims solutino would work if it was [self::class . '::__quotePath'] based on that article you linked to.

Which solution is best to go with and most backwards compatible for older versions please if either of you know? I don't have 8.2 to play around with currently so taking this on blind faith

Cheers
Jay

**Comment by osworx** [comment]
It works both - right now tested.
Use whatever you like.

**Comment by JAY6390** [comment]
@osworx @timint v2.6.8 released

**Comment by ubuntupunk** [comment]
I tried the fix above, but now I getting  `PHP Warning: Undefined array key 1`, for this line 455:

`return preg_quote($matches[1], '~');`

Is this connected or another issue?

**Comment by gudata** [comment]
I am getting the same error with PHP Version 8.4.12 and [v2.6.6-opencart](https://github.com/vqmod/vqmod/releases/tag/v2.6.6-opencart)
`PHP Warning: Undefined array key 1`

I am not getting an error with
`preg_replace_callback('~([^*]+)~', ['VQMod', '_quotePath'], $part);`


And then I found that there is a new repository for opencart vqmod : https://github.com/vqmod/opencart/releases/
