### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by sulrik** [vqmod/vqmod#173]
Hi,

my host provider has made some changes on server and after this all websites were broken with code 500. I've asked them to find the issue and they explained to me that the issue is this line of code in admin/index.php 

VQMod::bootup();

after they commented this line all pages has started to work fine, except admin page of my opencart store - I'm receiving error: VQMod::dirCheck - CANNOT CREATE "vqmod/logs/" DIRECTORY

Do you know maybe what is the problem and how to fix it?

**Comment by JAY6390** [comment]
It means your /vqmod/ directory doesn't have the correct permissions for writing to it. You will need to change it to allow write permissions for the server. Your host should be able to guide you on that. Alternatively, we can fix this for you for a $25 fee including making sure it's all set up and configured properly

**Comment by sulrik** [comment]
I’ve tried to change attributes  of this folder and it didn’t help

**Comment by JAY6390** [comment]
If that is the case, you'll need to find a developer that can help you with it as there may be a more complicated reason
