### ISSUE TITLE
Install problems (File manager opens instead of install script)

### ISSUE THREAD

**Issue by DachsbauTV** [vqmod/vqmod#174]
Hey hey,

I know this is probably less of a VQmod issue and more of a problem of me not knowing what to do, but maybe it could end up to be an addition to the install instructions :)

I've copied all of the files on to our namecheap server, but everytime I head to https://mydomain.com/store/vqmod/install the install script doesn't run and instead it would just show me the folder tree:
![Screenshot 2022-10-24 at 11 07 15](https://user-images.githubusercontent.com/70434961/197490421-bd94b9d9-c4f1-497a-8f0a-670cf4f04455.jpg)

Anyone could help me how to avoid this and actually install vqmod?

Thanks in advance

**Comment by JAY6390** [comment]
Looks like you haven't installed the opencart package, just the standard package. You need to install both as per the instructions

**Comment by DachsbauTV** [comment]
Ah okay I have it installed now.

Just as a tip: the instructions are a little misleading. It should rather say this:

`# opencart
This is a repository for the opencart vqmod core script files.
First download and copy vQmod from the main repository to your server, then copy the script files from this repository for use with opencart and place it in the same folder

1. Be sure you've copied the vQmod package first! This package only contains the opencart script files
2. Upload the xml and install folder to your vqmod folder on your server.
3. Overwrite any files that already exist

When done, you should see the following files on your server
	vqmod/xml/vqmod_opencart.xml
	vqmod/install/index.php

4. Run the installer with https:/yourstore.com/vqmod/install`
