### ISSUE TITLE
VQMod fails to apply modifications to the twig files included from other twig templates files.

### ISSUE THREAD

**Issue by deepvision7** [vqmod/vqmod#175]
VQMod 2.6.6 fails to apply modifications to the twig files included from other twig template files.
For example when `product card.twig` is included from the `category.twig` of the Journal3 template:

`{% include "journal3/template/journal3/product_card.twig" %}`

Although the file gets included by the twig engine and works fine although without any modifications applied in vqmod xml file. 

Besides that VQmod is able to modify twig files. The only problem is that modifications are not applied and the file `product_card.twig` does not appear in the `vqcache` folder. And it happens with any twig files that are included in that way.

What could it be please?
The site uses new twig engine  from OC 3.0.3.8 but it's heavily modified.

Thank you.

**Comment by JAY6390** [comment]
This is not something we can accommodate I'm afraid. In this instance you'd need to either switch the template file name using vqmod or add the code using some sort of replace on the template data after it's been built

**Comment by deepvision7** [comment]
VQMod was able to apply modifications for such included files until OC update. I think it has something to do with the new twig engine.
