### ISSUE TITLE
Two issues that need improvement

### ISSUE THREAD

**Issue by cchaoming** [vqmod/vqmod#182]
There are two aspects that cannot be met when using vqmod in other projects

(1) Directly replacing files to generate cache

(2) I want to replace a core class method using

<file name="vendor/topthink/framework/src/think/route/Url. php" info="test">

<operation>

<ignoreif position="replace" regex="true"><! [DATA [/public \ s+function \ s+build \ (\) \ s *: \ s * string (\ W)+\ {([\ s \ S] *) _ toString/i]]></ignoreif>

Replace Code

</add>

</operation>

</file> Prompt SEARCH NOT FOUND

But it can be found using this regularization in the editor, and later it was discovered that vqmod is searched line by line, not the entire text. I want the entire text to match and replace it. How to do this in xml? I hope to improve the above two points

**Comment by JAY6390** [comment]
VQMod uses a cache system. It won't overwrite actual files.
As for more than a single line, that's not possible to search as VQMods fundamental approach is line based

**Comment by cchaoming** [comment]
Solved it on my own thank you
https://github.com/cchaoming/php_vqmod/tree/master
