### ISSUE TITLE
updated wiki examples to include xml schema and syntax highlighting

### ISSUE THREAD

**Issue by Gamesh** [vqmod/vqmod#19]
you can merge them from my clone of your wiki
https://github.com/Gamesh/vqmod-wiki

or apply this git patch
https://gist.github.com/Gamesh/36b6088b146e195ebbe8

**Comment by Gamesh** [comment]
just to clarify, you won't merge those changes ?

**Comment by JAY6390** [comment]
Hi

Not at this time no. The highlighting we may add but the schema while useful to some is going to be largely wasted for the majority and therefore not worth adding in our opinion

Kind regards
Jay

**Comment by Gamesh** [comment]
i'll try to disagree. Currently there is no mod's XML validation, by adding XML schema the mods could be validated by the internal libxml for errors or miss-types in tag names or attribute names, in some cases in attribute values even. I personally had many times while using vqmod a misstype in my xml and vqmod just silently disregarded invalid tags. I think ability to validate mod's XML for errors would be useful for all.

**Comment by JAY6390** [comment]
I appreciate what you're saying, I just know for the most part that developers won't use it. It'll also add overhead to the vqmod loading process too

**Comment by Gamesh** [comment]
i see your point. if you would add $dom->schemaValidate() on each mod load, then all developers would use it, because the library uses it. you do a basic XML error handling by registering XML error handler anyway.

as for for the overhead, just to be fair i tested the speed.
DOMDocument::schemaValidate() with provided that XSD is a local file, with PHP 5.5 on windows
with 1000 iterations it takes on average 0.0010750s to validate the schema.
So if you have lets say 7 mods, it would add on total 0,007525s (7ms)
on a single core VM with PHP 5.4 debian linux it takes on average 0.0057963s to validate a single mod.

Well it's up to you, if you ever decide to reconsider the code will be there.

**Comment by JAY6390** [comment]
Thanks for the details. We do appreciate you providing the code and the load time examples. We may look at adding it in the next major iteration of VQMod, but for now we want to maintain backwards compatibility as far back as we can, and forcing the schema would break thousands of already coded mods unless they were edited - which as I'm sure you can appreciate is not going to go down too well :smiley:

**Comment by Gamesh** [comment]
i see what you are saying. Yes that would be not good. But unless you add the info to the wiki examples nobody will ever know about the schema and that they should use it. If you add schema to xml file currently without schemaValidate it does not break BC, it has absolutely no side effects.

**Comment by JAY6390** [comment]
OK I've gone ahead and copied your version of the wiki page for examples to include the xml schema :+1:

**Comment by Gamesh** [comment]
thanks
