### ISSUE TITLE
Replace behavior with index

### ISSUE THREAD

**Issue by veganista** [vqmod/vqmod#22]
Probably an edge case but just caught me out.

The below will not work as expected

```xml
    <file name="admin/controller/common/filemanager.php">
        <operation>
            <search position="replace" offset="5" index="1"><![CDATA[$allowed = array(]]></search>
            <add><![CDATA[
            $allowed = preg_replace('~\r?\n~', "\n", $this->config->get('config_file_ext_allowed'));
            $allowed = explode("\n", $allowed);
            ]]></add>
        </operation>
        <operation>
            <search position="replace" offset="6" index="2"><![CDATA[$allowed = array(]]></search>
            <add><![CDATA[
            $allowed = preg_replace('~\r?\n~', "\n", $this->config->get('config_file_mime_allowed'));
            $allowed = explode("\n", $allowed);
            ]]></add>
        </operation>
    </file>
```

I think its because when the second operation is applied the find now only exists once.

I had to change to the below to get this working. Note: I've had to change the `index` in the second find operation.

```xml
    <file name="admin/controller/common/filemanager.php">
        <operation>
            <search position="replace" offset="5" index="1"><![CDATA[$allowed = array(]]></search>
            <add><![CDATA[
            $allowed = preg_replace('~\r?\n~', "\n", $this->config->get('config_file_ext_allowed'));
            $allowed = explode("\n", $allowed);
            ]]></add>
        </operation>
        <operation>
            <search position="replace" offset="6" index="1"><![CDATA[$allowed = array(]]></search>
            <add><![CDATA[
            $allowed = preg_replace('~\r?\n~', "\n", $this->config->get('config_file_mime_allowed'));
            $allowed = explode("\n", $allowed);
            ]]></add>
        </operation>
    </file>
```

Might be worth noting in the wiki

**Comment by JAY6390** [comment]
This is actually already well known. Each operation is essentially working with the file at it's currently modified state, so two separate operations aren't aware of each other or their indexes. It's worth noting also that using replace with an offset is highly discouraged. What you're doing in your operation could almost certainly just be placed after all of the 5 lines and just override the allowed value. If you need it to not be set, you can place a start comment `/*` before the code and a `*/` after it but just removing chunks of code unnecessarily is not a good practice

**Comment by JAY6390** [comment]
Also, the alternative to the above is to simply do the operation on index 2 first then index 1

**Comment by veganista** [comment]
Ahhh, ok.

Cheers for the tips!
