### ISSUE TITLE
Is it possible that index.php is missing from install directory?

### ISSUE THREAD

**Issue by MikeiLL** [vqmod/vqmod#23]
I downloaded twice and it wasn't there. Once from download link and once with git clone.

**Comment by JAY6390** [comment]
Just downloaded and it is definitely there. Might be your anti virus is putting it in quarantine for some reason

**Comment by JAY6390** [comment]
Sorry just read this again - you said index.php not the vqmod.php file. What index.php are you expecting? the one in the /vqmod/install.php correct? if so, ensure you're downloading the opencart specific version and using the opencart branch if downloading directly

**Comment by MikeiLL** [comment]
Yes. The one in the install directory.

Maybe I wasn’t downloading the OpenCart specific one. I had copies of the files so copied index and a couple of other files that seemed to be missing after install as well. What exactly is the url, please to get to OpenCart specific one at?

**Comment by JAY6390** [comment]
https://github.com/vqmod/vqmod/releases
On this page, download the v2.5.1-opencart (not the standalone version)

**Comment by MikeiLL** [comment]
thanks!
