### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by rhtdm** [vqmod/vqmod#24]
I am trying to download but not able to download vqmod module.

**Comment by JAY6390** [comment]
VQMod is available from the [releases](https://github.com/vqmod/vqmod/releases) page. If you're using OpenCart you want the [vqmod-2.5.1-opencart.zip](https://github.com/vqmod/vqmod/releases/download/v2.5.1-opencart.zip/vqmod-2.5.1-opencart.zip) one

**Comment by rhtdm** [comment]
Still not able to download. Below is error details.
![11](https://cloud.githubusercontent.com/assets/11264599/6435811/3a5a873a-c0cb-11e4-9dd0-84f94f30bfd0.JPG)

**Comment by JAY6390** [comment]
That's likely down to your browser being so old. This is not an issue we can resolve

**Comment by JAY6390** [comment]
That's likely down to your browser being so old. This is not an issue we can resolve
