### ISSUE TITLE
about error_vqcache_files_missing

### ISSUE THREAD

**Issue by ramonliu** [vqmod/vqmod#26]
about "override_engine" variable, your condition depend on this file "/engine/factory.php" exist or not, 
in my opencart 2.0.1, this file not exist, so "override_engine" value is false.

at code last, near "check if vqcache files from vqmod_opencart.xml have been generated" block,
when I clear, these files auto created.
vq2-admin_controller_common_login.php
vq2-system_modification_system_engine_action.php
vq2-system_modification_system_engine_loader.php
vq2-system_modification_system_library_config.php
vq2-system_modification_system_library_language.php
vq2-system_startup.php

so you can see the problem... always at false block, 
these files does not exist...
vq2-system_engine_loader.php
vq2-system_library_language.php

**Comment by JAY6390** [comment]
There has never been an `engine/factory` element and your issue is nothing to do with VQMod - at least not the official one

**Comment by danielcotton** [comment]
For the benefit of the next poor soul that comes across this: engine/factory.php is part of the [OpenCart Override Engine](https://www.opencart.com/index.php?route=extension/extension/info&extension_id=8588)
