### ISSUE TITLE
OpenCart hosted in a subdirectory

### ISSUE THREAD

**Issue by PhilHudson** [vqmod/vqmod#29]
Should I expect vqmod not to work if my OpenCart shop's URL is ```mysite.tld/shop/``` rather than ```mysite.tld/```? Both your written and video instructions seem to assume the latter.

When I try to access ```mysite.tld/shop/vqmod/install```, I get:
```
Forbidden

You don't have permission to access /shop/vqmod/install/ on this server.
```
(note the trailing "/").

Every directory and file you mention has 755 permissions (even though I'm unconvinced that setting the execute permission on PHP files is necessary, useful or safe).

OpenCart 1.5.6
PHP 5.2.17
CentOS 5.10

**Comment by qphoria** [comment]
It works in either case. It's an example url. I also don't have an example
for .net or .org... Should you also assume it won't work for those?

You can set the vqmod folder to whatever chmod that works on your server.
Most folders are 755 by default so there isn't really anything to change or
worry about. You can take the foil hat off.
