### ISSUE TITLE
No errors, no logs, successful install

### ISSUE THREAD

**Issue by sporkman** [vqmod/vqmod#3]
I'm not sure if this is the correct place for more support-related questions, so close if not appropriate...

I have no problems with vqmod on our own hosting, but we have some demo sites that run on Hostway.

My problem with both an older vqmod version and the latest is that while the install completes successfully (I can see the edits to /index.php and /admin/index.php), I don't see any edits being applied.  The vqcache directory is empty as is the logs directory.  I've tried with default perms (755, which works for things like opencart's own cache and image dirs) and with overly permissive (777) perms for vqcache and logs directories.  I'm very confident all perms are correct at this point after going over things for a few hours and comparing to a working install.

Error display/logging is enabled in opencart, and not a single line logged/displayed.

Hostway does not seem to provide an actual apache error log, just an access log, but nothing of note there when fetching pages.

So my question is then how to debug when no errors are being logged?

**Comment by varsha63** [comment]
i am new here but i ask you one thing before so come here again pls guide me for this error 


on website vqmod success msg i already got but its not fetching vqmod/xml files

when i click edit on module i got this error :+1: 

Fatal error: Class 'ControllerModuleselleraccount' not found in /home/vikas140/public_html/admin/controller/extension/module.php on line 123


whats does this error means and how can i solve this . pls suggest something 

pls ans asap
