### ISSUE TITLE
VQMOD works with custom folder

### ISSUE THREAD

**Issue by saamalam** [vqmod/vqmod#30]
I've created a new folder on Opencart root directory called "POS". I've dozens of VQMOD .xml file that need to be work with the files with this POS folder. But unfortunately it is not working but it is working with admin, catalog, system etc folder.

Is there any way the vqmod works with the new folder called POS. Any suggestion will be helpful.

Thanks
saamalam@gmail.com

**Comment by JAY6390** [comment]
VQMod won't just work with a new folder unless you're including the files and running them through VQMod, just like the original files do

**Comment by saamalam** [comment]
I've already write the .xml file with the path  <file name="pos/controller/catalog/product.php">

it is not working. What do you mean by including the files and running them through vqmod. It seems VQMOD is unable to read the "pos" folder within the root of opencart. Can you assist me to solve this, i'm stuck for more than 3 days.

Thanks

**Comment by qphoria** [comment]
VQmod works during the "include" or "require" step in the opencart engine
files. If you want it to work for those files you need to have them
included from the pos folder. Look at the system/startup.php for examples.

**Comment by saamalam** [comment]
Gone through system/startup.php & vqcache/vq2-system_startup.php still no clue. 

Found from vqcache/vq2-system_startup.php
// Engine
require_once(VQMod::modCheck(DIR_SYSTEM . 'engine/action.php')); 
require_once(VQMod::modCheck(DIR_SYSTEM . 'engine/controller.php'));
require_once(VQMod::modCheck(DIR_SYSTEM . 'engine/front.php'));
require_once(VQMod::modCheck(DIR_SYSTEM . 'engine/loader.php')); 
require_once(VQMod::modCheck(DIR_SYSTEM . 'engine/model.php'));
require_once(VQMod::modCheck(DIR_SYSTEM . 'engine/registry.php'));

and Found from system/startup.php
// Engine
require_once(DIR_SYSTEM . 'engine/action.php'); 
require_once(DIR_SYSTEM . 'engine/controller.php');
require_once(DIR_SYSTEM . 'engine/front.php');
require_once(DIR_SYSTEM . 'engine/loader.php'); 
require_once(DIR_SYSTEM . 'engine/model.php');
require_once(DIR_SYSTEM . 'engine/registry.php');
---------------------------------------------------------------------------------------------



I'm not getting the point actually why the vqmod is just appliciable to opencart related directory only. However I've found some additional information from the file:
vqmod/vqmod.php

/**
	 * VQMod::path()
	 *
	 * @param string $path File path
	 * @param bool $skip_real If true path is full not relative
	 * @return bool, string
	 * @description Returns the full true path of a file if it exists, otherwise false
	 */
	public static function path($path, $skip_real = false) {
		$tmp = self::$_cwd . $path;
		$realpath = $skip_real ? $tmp : self::_realpath($tmp);
		if(!$realpath) {
			return false;
		}
		return $realpath;
	}

and 

/**
	 * VQMod::_realpath()
	 * 
	 * @param string $file
	 * @return string
	 * @description Returns real path of any path, adding directory slashes if necessary
	 */
	private static function _realpath($file) {
		$path = realpath($file);
		if(!file_exists($path)) {
			return false;
		}

		if(is_dir($path)) {
			$path = rtrim($path, self::$directorySeparator) . self::$directorySeparator;
		}

		return $path;
	}

and finally

private static $_doNotMod = array();


Still no luck how the vqmod is only appliciable to those opencart folders only.

Can anyone let me know how to make the VQMOD works with my custom folder named "pos"

**Comment by JAY6390** [comment]
https://github.com/vqmod/vqmod/wiki/Integration-with-Other-Platforms

**Comment by saamalam** [comment]
You DUMB developers including JAY6390,  qphoria and Daniel Kerr you don't deserve to be called as Developers.

Listen here's the solutions:

Just add this line to vqmod/install/index.php

// Add Admin index file
$u->addFile($pos . '/index.php');


that's it. good bye

**Comment by JAY6390** [comment]
What the fuck are you on about? You're clearly not strong enough as a developer to read basics and understand how a system works. The "Issues" section is for... that's right... issues. Not to hold your hand like a child through a very basic concept because you're not able to comprehend

**Comment by saamalam** [comment]
Fuck off you cock suckers, you haven't ability to solve the issues rather than you guys make the issues more complicated. You all show me the wrong way which was non-relevant to the solutions. You m***f** have no right to get in this group.

So go and fuck yourself and try to learn some OOP.
Jerk off

**Comment by JAY6390** [comment]
Yeah clearly we're the ones with the issues, that's why you're too retarded to read and yet are still using the software you're talking shit about

**Comment by saamalam** [comment]
fuck the software.......we are using you, and you'r being used. In near time you all will be outdated like win95. go and learn something before solving others issue

**Comment by qphoria** [comment]
Lol. /me grabs popcorn and watches the show

**Comment by opencarthelp** [comment]
I thought I'd seen some bad developer rage before but this one takes the cake (though "developer" may be too generous a term in this case).
