### ISSUE TITLE
vqmod fails without issuing any warning

### ISSUE THREAD

**Issue by torav** [vqmod/vqmod#32]
I use an svn repo to version my opencart website. I don't keep the vqcache/* and mods.cache files under versioning because they would constantly conflict with local versions. The last time I did a fresh checkout I first changed the permissions of the whole vqmod folder and then created the mods.cache file and then changed its permissions. Vqmod then stopped working without giving any log error whatsoever. It took me the best part of a hour to realise that the if statement in line 245 of the vqmod.php was leading to the "return" which prevented vqmod from working. 
What I did was probably not good practice (since I don't really need to change permissions for the whole vqmod folder), but nevertheless I think that vqmod should either issue a warning or write something in the logfile when the mods.cache file should not be empty but it is.

**Comment by JAY6390** [comment]
Hi

You shouldn't be creating the mods.cache file. This is why the vqmod folder itself needs to be writable. The same for checked.cache, and also so that the software can generate the necessary folders for logs/cache files

Kind regards
Jay

**Comment by torav** [comment]
Fair enough. While I think that no codes should silently fail without issuing any warning, I see why I shouldn't create those files myself. thank you!

**Comment by JAY6390** [comment]
Yes I understand what you are saying, it should do something at that point, though I'm not sure an error message is the best option. Perhaps it would be best to add in some code to disregard the cache file completely, and overwrite it. I think that was the original intention of the code there actually

Kind regards
Jay

**Comment by torav** [comment]
Yes, I think that could work. I know it's a very minor point, but I think that it may save other people from wasting time on it :-)
Thanks again!

best,
Lorenzo
