### ISSUE TITLE
cannot install vqmod on opencart

### ISSUE THREAD

**Issue by blasck** [vqmod/vqmod#33]
Hello,
I have run a opencart-based site on my rental host called ARVIXE,
the server is microsoft windows server 2012.
I followed the installing steps and finally it showed the error message like this:
"Parse error: syntax error, unexpected '/' in E:\HostingSpaces\pask\pask.com.tw\wwwroot\vqmod\install\index.php on line 93"
can anyone tell me what's going wrong?
Thank you.

**Comment by JAY6390** [comment]
This is going to be due to your windows server path not allowing realpath to work. You'll need to install manually as per the instructions on the wiki pages

**Comment by osworx** [comment]
What is wrong?
General: the Win* Server!

**Comment by blasck** [comment]
Well I follow the instructions of installing manually.
the front-end is okey,
but the admin-panel seems to be going wrong
it says:
"
Warning: mkdir() [function.mkdir]: No such file or directory in E:\HostingSpaces\pask\pask.com.tw\wwwroot\vqmod\vqmod.php on line 179
VQMod::dirCheck - CANNOT CREATE "vqmod/logs/" DIRECTORY
Warning: file_put_contents(vqmod/logs/0_Sun.log) [function.file-put-contents]: failed to open stream: No such file or directory in E:\HostingSpaces\pask\pask.com.tw\wwwroot\vqmod\vqmod.php on line 446
VQModLog::__destruct - LOG FILE "vqmod/logs/0_Sun.log" COULD NOT BE WRITTEN"

**Comment by JAY6390** [comment]
You've installed it incorrectly in your admin, most likely the path is wrong. Contact a developer if you need further help
