### ISSUE TITLE
cannot install vqmod on opencart

### ISSUE THREAD

**Issue by blasck** [vqmod/vqmod#34]
Well I follow the instructions of installing manually.
the front-end is okey,
but the admin-panel seems to be going wrong
it says:
"
Warning: mkdir() [function.mkdir]: No such file or directory in E:\HostingSpaces\pask\pask.com.tw\wwwroot\vqmod\vqmod.php on line 179
VQMod::dirCheck - CANNOT CREATE "vqmod/logs/" DIRECTORY
Warning: file_put_contents(vqmod/logs/0_Sun.log) [function.file-put-contents]: failed to open stream: No such file or directory in E:\HostingSpaces\pask\pask.com.tw\wwwroot\vqmod\vqmod.php on line 446
VQModLog::__destruct - LOG FILE "vqmod/logs/0_Sun.log" COULD NOT BE WRITTEN"

**Comment by JAY6390** [comment]
1. This isn't an issue - if it was you'd have it on both the customer and admin side
2. The issue section is for issues with the VQMod engine, not your installation. If you can't get it installed, contact a developer. It's provided as is
3. Don't open issues when you've got the same comment on your other issue report. They'll be ignored in the future
