### ISSUE TITLE
Administrator index.php not writeable

### ISSUE THREAD

**Issue by haxcop** [vqmod/vqmod#42]
Hi i'm using this installation locally on Ampps and it used to work fine but when i change the admin folder to "other" and try to reinstall the vqmod i got this error... i have use the pathreplaces.php acording the instructions and no luck... also i check the permisions 777 / 755  for the file index.php, change the path's on config's .php/ and no luck/ any idea :dart: ?

**Comment by kanenas** [comment]
Check this out `/vqmod/install/index.php` lines 32,33.

`// CHANGE THIS IF YOU EDIT YOUR ADMIN FOLDER NAME`
`$admin = 'admin';`

**Comment by haxcop** [comment]
Thanks! @kanenas :+1:  Works fine.
