### ISSUE TITLE
Parse error: syntax error, unexpected T_VARIABLE, expecting T_FUNCTION in vQmod

### ISSUE THREAD

**Issue by Bulldog51** [vqmod/vqmod#43]
I install vQmod on a working OpenCart 2.0.2.0 website and after installation I get the following error.
Parse error: syntax error, unexpected T_VARIABLE, expecting T_FUNCTION in /home/buyindus/public_html/ocart22/vqmod/vqcache/vq2-system_modification_catalog_controller_common_header.php on line 131
Can you point me in the right direction.

Bulldog51

**Comment by qphoria** [comment]
One of your vqmod xml scripts is buggy. Remove it. This has nothing to do
with vQmod engine.

**Comment by svschennai** [comment]
Dear Sir.
Account holder not seeing, his account from order link or click to order history . display below error:
Please how to solve the problem please help me:

Parse error: syntax error, unexpected ')' in /home/srivaishnavasric/public_html/vqmod/vqcache/vq2-catalog_controller_account_order.php on line 392

Thanking you
Your friendly
Muralidharan

**Comment by qphoria** [comment]
That is an error in somebody's vqmod script.. not in the vqmod engine. You need to contact the developer of the script for this.
