### ISSUE TITLE
opencart v2.5.0 or v2.5.1

### ISSUE THREAD

**Issue by renaissancejames** [vqmod/vqmod#44]
When I upgrade this, the site becomes unusable.

Displays an error of
Parse error: syntax error, unexpected ';' in /home/sclubley/public_html/eternaluk/vqmod/vqcache/vq2-system_modification_system_engine_action.php on line 58

Can anyone advise?

**Comment by jktoole** [comment]
This is an issue with the mod, not with vqmod itself.
1. Try deleting your cache on the offchance that that fixes it.
2. Identify which mod is causing the error by searching your mods folder - see if updating the mod to the latest version fixes the problem - and check if the mod is actually compatible with 2.5.1.
3. If that doesn't help, have a look around line 58 of "/home/sclubley/public_html/eternaluk/vqmod/vqcache/vq2-system_modification_system_engine_action.php" and then fix the error that's causing the problem in the mod xml file.

**Comment by JAY6390** [comment]
2.5.0 to 2.5.1 was just a very simple change in the `.htaccess` file 3507bb09c5a674f01c7f360dd2eb8133a70ca8c9. It has no effect on VQMod XMLs and the error you have is not from the upgrade to 2.5.1
