### ISSUE TITLE
showing Internal Server Error Opencart 2.0.3.1 

### ISSUE THREAD

**Issue by sureshkumarks1** [vqmod/vqmod#47]
After installing Vqmod cannot see the website. please check this link for more detail.
http://www.stylecatonline.com/demo/

**Comment by JAY6390** [comment]
This is an issue with your installation/server not the VQMod engine. You'll need to contact a developer to fix this for you

**Comment by sureshkumarks1** [comment]
hi,
thanks for the replay,
i am a php developer and i am using the server for the managing the site.
how can i fix this issue. please help me.


On 16 July 2015 at 15:32, JAY6390 <notifications@github.com> wrote:

> This is an issue with your installation/server not the VQMod engine.
> You'll need to contact a developer to fix this for you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vqmod/vqmod/issues/47#issuecomment-121914477>.
>



-- 
Thanks & Regards,
 Suresh Kumar .K.S.

**Comment by JAY6390** [comment]
Check with your host what error your server is giving to cause the 500 error
