### ISSUE TITLE
530Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket 

### ISSUE THREAD

**Issue by kiwisouvenirs** [vqmod/vqmod#5]
I am in the process of transferring my domain from www.kiwisouvenirs.com to  www.kiwisouvenirs.co.nz 

The new site is using the following  environment:
MySQL server version 5.5.34
Your PHP version is 5.5.

OpenCart © 2009-2014 All Rights Reserved. Version 1.5.6.4
vqmod-2.5.1-Opencart

and these extensions:

opencart seo pack pro v5.21---for-OC-1.5.4-+
Total Import PRO-OC v151
Zone Shipping PlusOC v153.2

Navigating the site seems okay until I try to place an order or make changes in admin in which case I get messages similar to the following error message caused when making a change to the price of a product and attempting to save the change.

An issue with VQMOD or 'user error'?

530Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 530Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 530Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 531Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 531Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 531Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 582Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 582Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 582Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 583Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 583Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 583Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 584Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 584Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 584Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 585Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 585Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 585Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 586Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 586Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 586Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 591Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 591Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 591Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 592Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 592Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 592Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 593Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 593Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 593Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 632Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 632Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 632Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 633Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 633Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 633Unknown: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 636Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (13) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 636Warning: mysql_real_escape_string(): A link to the server could not be established in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-admin_model_catalog_product.php on line 636Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/admin/index.php:85) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-system_engine_controller.php on line 28Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/admin/index.php:85) in /var/www/vhosts/kiwisouvenirs.co.nz/httpdocs/vqmod/vqcache/vq2-system_engine_controller.php on line 29

**Comment by bhaktadash248** [comment]
I created a site and its working properly and when i hosted the site in server at that time getting a bug
Deprecated: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/u101698811/public_html/login.php on line 4

Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory") in /home/u101698811/public_html/login.php on line 4

Warning: mysql_real_escape_string(): A link to the server could not be established in /home/u101698811/public_html/login.php on line 4

Please help me to fix this bug.

**Comment by JAY6390** [comment]
Not a VQMod issue. Contact a php professional
