### ISSUE TITLE
vqmod open cart double extension front end display

### ISSUE THREAD

**Issue by thesquaremedia** [vqmod/vqmod#50]
Hi i deleted an extension xml and reuplaoded it why would the replied give me vqcache errors as if its redeclared and display double on the front end of open cart. Seems to me as if there are two instances of the extension. could i get some guidance on the vqmod open cart side. I know you cant help me specifically on the extension but i figure you could have some guidance on the vqmod side

**Comment by JAY6390** [comment]
If you are using opencart 2 the only reason would be if you have a cached version in the OCMod version somehow. Other than that, it can't happen without two VQMod xmls being uploaded

**Comment by thesquaremedia** [comment]
that was totally it thanks i just deleted(moved them into a backup folder) the files under system/modifications and it totally solved the issues
