### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by bhaktadash248** [vqmod/vqmod#52]
I created a site and its working properly in local server and when i hosted the site in server at that time getting bugs.
Deprecated: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/u101698811/public_html/login.php on line 4

Warning: mysql_real_escape_string(): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory") in /home/u101698811/public_html/login.php on line 4

Warning: mysql_real_escape_string(): A link to the server could not be established in /home/u101698811/public_html/login.php on line 4

Please help me to fix this bug.

**Comment by jktoole** [comment]
This seems more like a problem with your server and/or database setup (and that you're using an old mysql extension). Nothing you've posted is related to vqmod.

Try asking in the support forum for your hosting provider, or the support forum for whatever script it is that you're applying vqmod to.

**Comment by JAY6390** [comment]
Not VQMod related
