### ISSUE TITLE
[Feature Request] Support VQMod Files In OC2.0 Extension Installer

### ISSUE THREAD

**Issue by OpenCartAddons** [vqmod/vqmod#56]
I finally used the OpenCart v2.0 extension installer and realized that it doesn't support the installation of VQMod files.

Perhaps this is something you guys could look into adding as part of opencart.xml in the download package.

Cheers,
Joel.

**Comment by susanlummis** [comment]
I'm out of the office until Monday 7th September.  For urgent issues contact steve@puckator.co.uk

**Comment by qphoria** [comment]
This is solely up to opencart to decide. We could make a vQmod to add
support but it seems cyclic.

**Comment by OpenCartAddons** [comment]
@qphoria I get what you mean

Cheers,
Joel

**Comment by qphoria** [comment]
In any case, I created a script to do it
http://forum.opencart.com/viewtopic.php?f=131&t=151298

**Comment by OpenCartAddons** [comment]
@qphoria Nicely done sir.  Very much appreciated.

Would this be packaged with vQmod, or will this be a separate mod download?


Regards,
Joel.

**Comment by qphoria** [comment]
This will only stay on the forum.
