### ISSUE TITLE
Admin Lockout of Opencart by vqmod

### ISSUE THREAD

**Issue by ShaneSheppard** [vqmod/vqmod#59]
Hello,

My site is currently working but i have no access to open cart (1.5.6.4), the login page comes up with this fatal error.

Fatal error: Call to a member function getId() on a non-object in /public_html/vqmod/vqcache/vq2-catalog_controller_common_footer.php on line 145

Do you have any clue how to fix this or what to do as a starting point?

Kind Regards,
Shane S

**Comment by qphoria** [comment]
This is due to a vQmod script by a 3rd party author, not the vQmod engine.
Disable any new scripts you've added to the xml folder or just keep
reminding them one by one, except for the vqmod_opencart.xml file, until
you find it. Then contact the author of that script.

Q

**Comment by ShaneSheppard** [comment]
This did the trick it was a third party script.
You can close this now, Thank You!
