### ISSUE TITLE
How to install vqmod on OpenCart is broken

### ISSUE THREAD

**Issue by alovak** [vqmod/vqmod#60]
Hello! I have found that instructions and video of [how to install vqmod on opencart](https://github.com/vqmod/vqmod/wiki/Installing-vQmod-on-OpenCart) is outdated.

If you download vqmod for opencart from https://github.com/vqmod/vqmod/releases you will find that vqmod/install does not contain index.php file. There are a separate files for opencart in archive /platforms/opencart that should be uploaded into vqmod folder too.

So https://github.com/vqmod/vqmod/wiki/Installing-vQmod-on-OpenCart should be updated or archive should be fixed.

**Comment by JAY6390** [comment]
If you download the correct version (the opencart install not the standalone version) then yes it does contain the index.php

**Comment by alovak** [comment]
@JAY6390 you are right. I didn't now want to download zip file but tar.gz... and it brought me to 'Source code' download... do you think I'm the only one having this problem? :)

**Comment by JAY6390** [comment]
Possibly not, however we cannot actually stop the source code links on the downloads unfortunately on that page
