### ISSUE TITLE
please add the install/index.php file in master branch and update releases in code.google.com

### ISSUE THREAD

**Issue by nikto1** [vqmod/vqmod#62]
Most people download vqmod from https://code.google.com/p/vqmod/downloads/list , but there's still the old version of vqmod.
Also, please update the masterbranch where's missing the index.php file in the install folder.

Great thanks.

**Comment by JAY6390** [comment]
We cannot upload to google code any more, as the site will close early next year. And we aren't putting any opencart based files in the master branch as they are only specific to that software. Other software such as litecart also use VQMod and don't use the installer

**Comment by JAY6390** [comment]
Oh and the whole of the google code site for us is now in read-only mode so we can't even delete the downloads from there

**Comment by nikto1** [comment]
1) Maybe it would ne good to add a message to google code as i see the most links pointing to code.google.com. I also knew it only because a customer contacted me that vqmod wasn't working. Sure, because he downloaded an old version from code.google.com
2) With the index.php i obviously meant the index file in vqmod-master/install/ folder. In this folder there's only ugrsr.class.php but no index.php. See screenshot below.
![screen](https://cloud.githubusercontent.com/assets/9814101/10409988/d34dcd78-6f33-11e5-8530-246b7acf20b0.jpg)

Anyway great work done with vqmod. 
Have a nice day

**Comment by JAY6390** [comment]
Hi

Again - We *cannot* edit the google code pages - it's read only meaning no changes at all can be done. You'll also note that we did put a message on the google code homepage saying we've moved to github. We couldn't put a message on the downloads page.

For the installer `index.php` file, it *is* in the directory for the *OpenCart* branch
https://github.com/vqmod/vqmod/tree/opencart/vqmod/install

You have the 'master' branch which is not OpenCart compatible out of the box for the reasons I gave above. You're also missing the `/vqmod/xml/vqmod_opencart.xml` file

Kind regards
Jay

**Comment by nikto1** [comment]
Hi, 
for me it's ok, no problem. Generally i include vqmod in my packages to make the installation process faster and easier. Just were thinking about other users.
But after this discussion people will find the install package easier :-)
Thanks anyway for the attention.

Kind Regards
