### ISSUE TITLE
Error listing

### ISSUE THREAD

**Issue by SkitterbugArts** [vqmod/vqmod#63]
2015-10-02 19:59:31 - PHP Notice:  Undefined variable: product_id in /home3/fwngdxze/public_html/store/vqmod/vqcache/vq2-catalog_controller_product_product.php on line 701

This is line 700-701
700 if (isset($this->error['keyword'])) {
701 $data['error_keyword'] = $this->error['keyword'];

Trying to upload audio using 2.0.3 audio player: http://www.opencart.com/index.php?route=extension/extension/info&extension_id=12148&filter_search=media%20player

**Comment by JAY6390** [comment]
Nothing to do with the VQMod engine. This is a vqmod xml extension you've downloaded from somewhere and as such you need to contact them for help

**Comment by SkitterbugArts** [comment]
I downloaded it from GitHub.

On Fri, Oct 9, 2015 at 2:13 PM, JAY6390 <notifications@github.com> wrote:

> Nothing to do with the VQMod engine. This is a vqmod xml extension you've
> downloaded from somewhere and as such you need to contact them for help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vqmod/vqmod/issues/63#issuecomment-146951563>.
>



-- 
Peace,
Bryn Sowash
*Founder*

*Skitterbug LLC*
*Support for Creative Professionals*
(614) 450-2843 I bryn@skitterbug.co <info@skitterbug.co>
skitterbug.co

*FREE eBook!*
Virtual Visionary: A Guide to Web Presence for Creatives
<http://skitterbug.co/free-pdf-guide-to-web-presence-for-creative-professionals/>

<https://www.facebook.com/skitterbughelp>
<https://twitter.com/skitterbughelp>
<https://www.linkedin.com/profile/view?id=126774381&trk=nav_responsive_tab_profile>

**Comment by JAY6390** [comment]
That may be so, but you certainly didn't download whatever is causing that error from this github projects repository
