### ISSUE TITLE
List file modifed by xml

### ISSUE THREAD

**Issue by agung-wete** [vqmod/vqmod#64]
Sometimes when debugging, there's needs to find which xml change the file.
Maybe we can add some variable to save this info ?
thank you

**Comment by JAY6390** [comment]
This is pretty easy to do using a text editor. Open the mods.cache file and search for the code that is unique to that change. Then search backwards in the mods.cache file for `.xml` and that will be the vqmod. This isn't a bug so closing

**Comment by agung-wete** [comment]
I have modified it to suit my need. I'm paste here incase someone need it : 

https://gist.github.com/agung-wete/8d20d3fa0e7ca714d8e0
