### ISSUE TITLE
vqchache for Opencart 2.0.x generates a Notice after adding payment getway - countryid and zoneid

### ISSUE THREAD

**Issue by ian15brown** [vqmod/vqmod#65]
Hi,
I get a Notice after adding payment gateway to opencart installation  on Check Out page at payment step. I did set Geozone to Global.

Notice: Undefined index: country_id in /home/***/public_html/vqmod/vqcache/vq2-catalog_model_checkout_order.php on line 1960

Notice: Undefined index: zone_id in /home/***/public_html/vqmod/vqcache/vq2-catalog_model_checkout_order.php on line 1961

Could you help suggest a solution.

Cheers,
Ian

![vqmod-chache](https://cloud.githubusercontent.com/assets/15243427/10658495/f95eb640-78c9-11e5-946c-dcbc65390d18.jpg)

**Comment by PeteAUK** [comment]
There's an issue with one of your extensions rather than vQMod.  Have a look at any extensions that relate to your checkout.

**Comment by JAY6390** [comment]
This isn't a general help forum, especially for opencart. And the error you've given in no way has anything to do with VQMod. Contact a professional to help you or post on the opencart forums
