### ISSUE TITLE
how to check Is vqmod working fine or any issue  

### ISSUE THREAD

**Issue by kalpeshdesai20** [vqmod/vqmod#66]
I am using oc v2.1.0.1 and vqmod latest version.
I am getting issue with some extensions not working after successfully installed.
I took support from all extensions accordingly, all are saying same thing that my vqmod is not working properly.
I don't have any idea whether it is working properly or not and how to know what exactly problem is.
How to know whether vqmod working fine or not ?
Please help me.
my site is live and I am getting issue.
site is : www.shoppincent.com
thank you

**Comment by BinotaLiu** [comment]
try to check vqmod's cache directory,
it's `vqmod/vqcache` by default,
if your install is work, there will be some file there.

**Comment by kalpeshdesai20** [comment]
there are so many files there. actually it seems working everything file but so many new extensions not getting worked. If any issue will be there, how to know ? is there any error log ?

**Comment by kalpeshdesai20** [comment]
I can share my login detail if this is not public ticket.

**Comment by kalpeshdesai20** [comment]
Is there any conflict between ocmod and vqmod ?

**Comment by qphoria** [comment]
Please email ftp details to qphoria@gmail.com

**Comment by kalpeshdesai20** [comment]
ok sure thank you for responding quick.

**Comment by qphoria** [comment]
No

**Comment by kalpeshdesai20** [comment]
Did u find any issue ?
Thank u.

**Comment by sull** [comment]
fwiw, I too am having problems with a fresh install of OC 2.1 and latest VQMod with some extensions that I am trying to test. 

Currently, the only file that gets added to the cache dir is vq2-system_library_customer.php. 
VQMod reports it is successfully installed and checking index files, it has the modifications from the install file. I also added additional lines based on the manual install instructions (// Application Classes...)

**Comment by qphoria** [comment]
Set me up with ftp access and I'll take a look. There are no issues with
2.1 and vqmod
Contact me directly at qphoria =at=   -- gmail== dot -com
Don't put it in this reply

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by JAY6390** [comment]
Out of interest are either of you using the Journal 2 theme?
Kind regardsJay

-------- Original message --------

**Comment by sull** [comment]
It appears my issue was not VQMod. It just seemed that way. 
I am using fresh install default theme. 

After I installed this:
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22378

I was alerted that an extension that was installed was missing some db table and it attempted to reinstall. That seemed to fix some problems.

**Comment by blackdesignstyle** [comment]
I have download the extension from here. I use Opencart 2.1.0.1. I Enter the www.domain.com/vqmod/install/ it says: VQMOD ALREADY INSTALLED!

But I can not see the extension under the modules or anywhere. I also check the permiss.on of admin.

**Comment by JAY6390** [comment]
@blackdesignstyle VQMod doesn't have an admin interface of any kind. If you want something for that I suggest VQModerator or VQMod Manager

**Comment by qphoria** [comment]
Best way to check if it works
Install it
Refresh your home page
goto ftp and see if you see anything being created in vqmod/vqcache
If so, then you are good.


Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by blackdesignstyle** [comment]
@qphoria Yes, I can see some files in vqmod/vqcache/..
There is 5 files in there. library, engine and startup files. Thank you.
