### ISSUE TITLE
Cannot install vqmod

### ISSUE THREAD

**Issue by tolitscc** [vqmod/vqmod#67]
Installation instruction has vqmod/vqcache folder but downloaded file do not have this folder. Displays only the contents of the directory.  See the attached image.
![vq](https://cloud.githubusercontent.com/assets/4786490/11973041/a01ff200-a98f-11e5-869e-77027a88f7f2.jpg)

**Comment by JAY6390** [comment]
The directory is created automatically, if write permissions are set correctly
