### ISSUE TITLE
VQMod extensions not showing in admin menu

### ISSUE THREAD

**Issue by mrblp** [vqmod/vqmod#68]
Hi,

I installed VQMod and some exentions to Opencart 1.5.5.1 .
All data is from the old host, and everything was pulled from the FTP server without errors or warnings. 
Everything works perfectly, except the stock mod which requires VQMod. 
It's installed in the module menu, the data in the database is exactly what it's supposed to be, it only doesn't show up in the admin menu.

Anything you can do to help?

Much appreciated, 
Bram

**Comment by JAY6390** [comment]
You need to contact the developer of the VQMod extension. We are the developers of the engine itself that reads the extension files. We have nothing to do with a stock mod and I wouldn't even know which extension you are referring to, nor do we give support for anything except the vqmod engine code
