### ISSUE TITLE
VqMod not regenerating cache properly

### ISSUE THREAD

**Issue by supak111** [vqmod/vqmod#69]
Hey guys I can get vqmod to regenerate my vqmod caches correctly.  I edited my footer.tpl file to add some code there but no matter what I do vqmod keeps making a new footer.tpl file that doesn't have the new code in it.  Only way to make the code in footer.tpl file appear on my site is if I add the code to the footer.tpl file inside vqmod/vqcache folder.

I've tried deleting all the vqmod caches but no help.  I've tried refreshing cache in admin/modification still not help.  If I delete mods.cache the code I added in vqmod/vqcache  footer.tpl gets deleted.  What could be causing my vqmod/cache not to generate correctly?

**Comment by JAY6390** [comment]
You don't add code to the cache files, you make XML files which then add the code in the cache files

**Comment by supak111** [comment]
I shouldn't have to add the code to the cache files.  If I edit catalog/view/there/default/template/common/footer.tpl  shouldn't that code then appear in my cache.  I should be able to edit my footer.tpl and have that code appear on my website but it does not.

**Comment by supak111** [comment]
for some reason vqmod keeps generating cache with out the code I added to footer.tpl file in catalog/view/there/default/template/common/footer.tpl

**Comment by JAY6390** [comment]
Assuming you're using OpenCart 2 you will need to clear your modifications cache under EXTENSIONS > MODIFICATIONS when you edit your template files directly. This is the last I'm saying on the matter as this has nothing to do with VQMod and VQMod's engine works just fine when used properly

**Comment by supak111** [comment]
I've tried everything.   I've cleared them and refreshed them 10 times.  But thanks for your 2 cent bud.
