### ISSUE TITLE
vqmod 403 error when installing

### ISSUE THREAD

**Issue by badsyntaxx** [vqmod/vqmod#70]
Hello I have a problem installing vqmod. It should be very simple following the instructions on github I have placed the vqmod directory in my root. However when I navigate to mysite.com/vqmod/install I get a 403 forbidden error.

After searching my error I found a number of solutions none of which work for me.

I have set the file permissions to both 777 and 755

I have altered the htaccess file inside vqmod directory to allow

I also removed Options -Indexes from htaccess in my root directory to allow seeing the vqmod directory but still mysite.com/vqmod/install still says 403 forbidden

I also tried manual install but the files in github install manual don't match my own.
my index files in root and under admin only have the startup line and do not contain anything under and including // Application Classes

My host is rackspace running linux / apache / php5.4

opencart v2.0.1.1

vqmod 2.5.2

Why does nothing work. vqmod supposed to be drag and drop install. Shouldn't be anywhere near this diffcult. Am I missing something?

**Comment by CheloARG** [comment]
Same thing here.

It should be very simple but I'm still getting 403 fobidden error.

**Comment by badsyntaxx** [comment]
Hey CheloARG. I figured out what was going wrong for me. The install instructions are horrifically bad. You cannot just choose download any install folder with opencart in the title like the installation instructions say. Try this page https://github.com/vqmod/vqmod/releases. Try the link titled vqmod-2.5.1-opencart.zip. Whoever wrote the install instructions failed pretty hard.

**Comment by CheloARG** [comment]
Thanks a lot dude! Someone told me the same thing a few hours ago and yeah, seems that instructions are wrong and probably the vQmod file in OpenCart webiste is wrong too.

Thanks agaiN!

**Comment by qphoria** [comment]
I fail to understand your issue. The install directions say "install the version with opencart in the title". It should be obvious that you grab the latest version.

**Comment by CheloARG** [comment]
Read the previous comment.

**Comment by JAY6390** [comment]
You don't need to create the vqcache folder as badsyntaxx said. The VQMod directory needs to have write permissions in order to create it automatically for you. Same for the logs directory. You shouldn't be downloading code from anywhere other than the releases page, as the front page of this github repo says - specifically the opencart one if you are using OC. Where exactly did you download it from if not from there?

**Comment by CheloARG** [comment]
I've downloaded it from OpenCart website, they provide a link to directly download the one that works with OC, apparently it has some files missing inside and that's what causing me trouble. Nevermind, I already solved it by downloading the correct one from the vQmod website, as already said.

**Comment by JAY6390** [comment]
@CheloARG - any chance you know where exactly? There shouldn't be any downloads for VQMod other than this site. There are some horrific edits of it that try and merge it with ocmod but they don't work well and shouldn't be used

**Comment by CheloARG** [comment]
I'm not sure but I think here (http://www.opencart.com/index.php?route=extension/extension/info&extension_id=19501).
Anyway, instructions here (http://docs.opencart.com/administration/vqmod/) are confusing.

**Comment by JAY6390** [comment]
OK thanks. Yeah the extension given is not an official release and is one of the frankenstein versions I mentioned above. The docs are also not offical ones. Our official docs are in the [Wiki](https://github.com/vqmod/vqmod/wiki)

**Comment by CheloARG** [comment]
Yeah I could notice that. I'm a newbie so I was confident with OC docs and links. Since instructions were easy to follow, it was weird I couldn't make it work.
I've sent an email to OC so they can modify both instructions and downloads.

**Comment by bkrajendra** [comment]
I dont understand what going on here. How come any file run without index.php in folder.
there is no index.php in install folder and thats why my server giver error Forbidden.
Can any one help on this?

**Comment by IP-CAM** [comment]
Better find out first, how VqMod works, and then, add some usable information on what Software and Version you use, as well as the VqMod Version, if you expect  valuable reply.

**Comment by osworx** [comment]
> 
> 
> I dont understand what going on here. How come any file run without index.php in folder.
> there is no index.php in install folder and thats why my server giver error Forbidden.
> Can any one help on this?

But all others here before you, were able to read the installation guide:
https://github.com/vqmod/vqmod/wiki/Installing-vQmod-on-OpenCart

After you have read this, you are allowed to ask questions here .. ;)

**Comment by bkrajendra** [comment]
I did read everything and then only came here to comment.
It was all my frustration which made me comment in way i did above.
I should definitely apologize and agree with you all.

But don't you think its very easy to miss very important instruction? 
My suggestion is to format the instruction or release page in a way it should be clear what to download.

Mostly its very common to have release type (standalone and opencart) assets included in every release.
I have first time seen that the release page has two different release type at two releases with same version.
And I have tendency to run for latest version ... and that's where i hv gone wrong.

For sure I made two mistakes:
1) I could not see and understand the instruction at line:
```
1 Download the latest version that has "opencart" in the title from the releases page.
```
2) I failed to understand release page: 

But Many people are getting same issue (Forbidden) which means we can give it thought to make it little clear.
👍

**Comment by bkrajendra** [comment]
Just in case any one come in search of solution:
1) Read the instructions no 1 carefully at https://github.com/vqmod/vqmod/wiki/Installing-vQmod-on-OpenCart
2) On release page there are two seperate releases for two different options

- Basic vQmod without any integration
- OpenCart integration of vQmod
Opencart user should download second release vqmod-x.x.x-**opencart**.zip file

3) Mostly no need to set any permission on index.php file. In my case setting 755 and 777 permissions create more issue, as on my server changing permission for php file other than 644 throws error.
Im on centos 7+ with Apache and php 7.2+, OC Version 3.0.3.2
4) Everything worked for me without any issue after following rest of the instructions.
