### ISSUE TITLE
changes for system/library/cart/cart.php will not work

### ISSUE THREAD

**Issue by douse** [vqmod/vqmod#73]
vqmod will not generate a vqcache-file for changes in system/library/cart/cart.php in OC 2.1.0.2, so my modifaction is not working ... 

I think the new cart-subfolder is the issue.

Can you fix this ?

**Comment by qphoria** [comment]
2.1.0.2 doesn't have a cart subfolder in library. You are taking about
2.2.0.0 which hasn't been released yet. When it is, we will look into it

**Comment by osworx** [comment]
No, what he wrote is correct.
This user has created as test a new folder inside ```library``` called ```cart``` (could be also test or what ever ..) and inside that new folder he has placed the testfile ```cart.php``` (could be also test.php).
VQMod (current stable version) is not able to change that file (tested and confirmed).

**Comment by douse** [comment]
no, it's right, i checked this. in the blank OC 2.1.0.2. is no cart-folder.
I think, i got the cart folder from an previous installation (github-version). sorry, my fault ;)

**Comment by osworx** [comment]
Nevertheless, if a subfolder inside the ```../system/library/ ``` exists (does no matter for what reason), VQMod does not take care of these files.

**Comment by JAY6390** [comment]
All files that come standard with 2.1.x work fine. The only reason any files there wouldn't be loaded would be if they're not loaded in the standard fashion that OpenCart loads lib files
