### ISSUE TITLE
vqmod manual install files do not match opencart files

### ISSUE THREAD

**Issue by badsyntaxx** [vqmod/vqmod#74]
For some reason the autoinstaller will not work on my host. Im trying to manual install but the files do not match. I even downloaded a fresh copy of opencart 2 and the files do not match.

In the fail example on the github page it says find this inside index.php
`
// Startup
  require_once(DIR_SYSTEM . 'startup.php');

  // Application Classes
  require_once(DIR_SYSTEM . 'library/customer.php');
  require_once(DIR_SYSTEM . 'library/currency.php');
  require_once(DIR_SYSTEM . 'library/tax.php');
  require_once(DIR_SYSTEM . 'library/weight.php');
  require_once(DIR_SYSTEM . 'library/length.php');
  require_once(DIR_SYSTEM . 'library/cart.php');
  require_once(DIR_SYSTEM . 'library/affiliate.php');
`

In the actual opencart index.php
`
// Startup
require_once(DIR_SYSTEM . 'startup.php');

// Registry
$registry = new Registry();

// Loader
$loader = new Loader($registry);
$registry->set('load', $loader);
`
Is the manual install instruction outdated?

**Comment by qphoria** [comment]
I've updated the steps for 2.x format

Cheers,

Tom "Qphoria"
OpenCartGuru.com
