### ISSUE TITLE
VQMOD - Problem after installation

### ISSUE THREAD

**Issue by monbrastudio** [vqmod/vqmod#75]
Hello, i follow all steps to install vqmod, after ALREADY INSTALLED TEST my website show this message "Fatal error: Cannot instantiate abstract class VQMod in /web/htdocs/www.casadellapesca.com/home/admin/index.php on line 16"

Can you help me?

http://www.casadellapesca.com/admin/

thank you

**Comment by qphoria** [comment]
Run the installer again

**Comment by monbrastudio** [comment]
ho provato ma non funziona ancora, da sempre lo stesso messaggio

**Comment by monbrastudio** [comment]
i try but have the same problem

**Comment by qphoria** [comment]
Then you likely didn't download the opencart version of the mod that comes
with the updated installer

**Comment by monbrastudio** [comment]
can you help me to restore the old versione. My site is down :(

**Comment by qphoria** [comment]
set me up with ftp access and email to qphoria@gmail.com
do not reply to this email as it is public.

Cheers,

Tom "Qphoria"
OpenCartGuru.com
