### ISSUE TITLE
vqmod and new extention

### ISSUE THREAD

**Issue by famarinu** [vqmod/vqmod#76]
Dear,
I'm using Opencart 2.1.0.1 and I installed a new module that gives me this problem:
Notice: Undefined index: value in the ... / eshop / vqmod / vqcache / VQ2-system_library_cart.php online 372Notice: Undefined index: value in the ... / eshop / vqmod / vqcache / VQ2-system_library_cart.php on line 468

It is written in the form of installation files:
if you have vqcache enabled, delete all files under vqmod / vqcache.

But I would not want the deletion of these files I create other problems, so I wonder what happens if I delete these files?
Can I delete only the VQ2-system_library_cart.php files?
Can I uninstall vqmod?

**Comment by famarinu** [comment]
Inside the vqmod / log folder I found this log file:

---------- Date: 02/02/2016 06:44:12 ~ IP: xxxxxxxxxxxx ----------
REQUEST URI: / eshop /
MOD DETAILS:
   modFile: ... / eshop / vqmod / xml / voucher-on-purchase.xml
   id: Voucher On Purchase-ocv2
   version: 1.2
   vqmver: 1.0.8
   author: kodecube.com
VQModObject :: parseMods - Could not resolve path for [catalog / model / checkout / voucher.php] (SKIPPED)
VQModObject :: parseMods - Could not resolve path for [catalog / controller / checkout / checkout_two.php] (SKIPPED)
-------------------------------------------------- --------------------


---------- Date: 02/02/2016 09:10:05 ~ IP: 94205211253 ----------
REQUEST URI: /eshop/admin/index.php?route=extension/installer/php&token=SKxHLj7A1tTBAnUzYQN2SU1t0qX8zTFI
MOD DETAILS:
   modFile: ... / eshop / vqmod / xml / voucher-on-purchase.xml
   id: Voucher On Purchase-ocv2
   version: 1.2
   vqmver: 1.0.8
   author: kodecube.com
VQModObject :: parseMods - Could not resolve path for [catalog / model / checkout / voucher.php] (SKIPPED)
VQModObject :: parseMods - Could not resolve path for [catalog / controller / checkout / checkout_two.php] (SKIPPED)
-------------------------------------------------- --------------------

Can it help me solve the problem?

**Comment by sculptex** [comment]
The two files is mentions;
catalog / model / checkout / voucher.php
catalog / controller / checkout / checkout_two.php
do not exist on a standard installation. Your mod may require these files to be uploaded by ftp.

**Comment by JAY6390** [comment]
Not an engine issue. Closing
