### ISSUE TITLE
OpenCart version tag

### ISSUE THREAD

**Issue by thekrotek** [vqmod/vqmod#78]
Since VQMod now supports both OC 1.5 and 2.0 versions, could you add some tag or parameter to define, which part of XML should be parsed on this particular version?

The main purpose of it is to avoid creating 2 vqmod files and simplify installation. Right now you need to have 2 vqmod files and you can't put them both in vqmod/xml folder without risk of having multiple "cannot redeclare" errors. But if we had a version tag, this would solve the problem. Something like this:

<file name="file.php" version="2">

Version parameter can be 1 or 2 for all versions or particular OC version (e.g.: 2.1 for all 2.1 versions or 2.1.0.1 for this version only).

I know, that there's a limitation to XML size and this parameter can increase your chances to hit this limit. But hey, we can always create two XML files and split the code. It's much easier, that always work with 2 files.

I think it'll make like easier for developers and for customers as well.

**Comment by qphoria** [comment]
vQmod is platform and version agnostic.
It doesn't know what opencart is nor what 1.5 or 2.0 is
What you can do is add the conditional as part of your code
First find something common between both versions

<search>somethingcommon</search>

<add>
if (version_compare(VERSION, '2.0', '>=')) {
    do something 20ish
} else {
    do something 15xish
}
</add>

Try being creative at the php level before worrying about the vQmod level.
Think how you would hardcode a mod across 2 versions, then create it as a
vQmod

Q

**Comment by thekrotek** [comment]
That's not what I meant. I wasn't talking about version compare, of which I, of course, pretty much aware. I was talking about **search strings and file paths**. For OC 1.5 it can be one search string and path, for OC 2.0 another and for OC 2.1 a third one.

If I put in XML file for OC 1.5 path or search string from OC 2.0, it'll produce an error. Even if I put error="skip", it'll still add an entry to log and half of the customers will ask me, what does this error mean. And I'll have to explain them, that it is skipped, blah-blah-blah. This happens all the time for modifications in TPL-files.

With version tag VQMod could simply ignore unrelated stuff and don't even log it. This is my point.

**Comment by thekrotek** [comment]
And I'm pretty sure it's quite easy to add OC version check in VQMod parser. I could even do this myself, but this has no sense at all, since people download original VQMod from you.

**Comment by qphoria** [comment]
Then get creative with the operation tag and use error="skip"
Then you can have 2 diff operations based on the search and it will ignore
it.
So you can have one operation search for something only in 1.5.x
if it finds it, it will apply the change. If it doesn't find it, it will
skip it
another operation can search for 2.x
if it finds it, it will apply the change. If it doesn't find it, it will
skip it

Now you can have a single file that covers both versions.
The caveat being that you lose the default logging of actual conflict
errors.

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by qphoria** [comment]
Again, vQmod is platform agnostic. vQmod can potentially be used with any
php platform. Wordpress, phpbb, joomla, etc. It is not sensible for us to
support specifics from a single platform as it is meant to be generic.

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by thekrotek** [comment]
There's an OpenCart specific VQMod, isn't it? I was talking about this particular VQMod version, not the one that platform agnostic or whatsoever.

And like I said before, error="skip" still produce log entries sometimes. It just says SKIPPED and then customers send me questions about it. Might be related to other VQMod parsers though, because there weren't such issue on OC 1.5. Only OC 2.0 with its stupid OCMod and bunch of VQMod managers/parsers on the market started to produce this stuff.

**There's a drawback of error tag as well!** But first, let's skip "be creative" part, because you didn't see my VQMods and have no idea, how creative I am. Trust me, I'm VERY creative with VQmods and don't require any lectures on it. So let's get strictly to business.

Let's say, I will create a generic VQMod file for both versions. To avoid errors in log, I will put error="skip" for EVERY entry. I'm pretty sure, you understand, what will be the result: not a single error will be displayed, even the real one and even for proper version. This is why I'm suggesting a new tag to define, which OC version is requested.

Once again:

- There's a VQMod for OpenCart, an OpenCart specific version of VQmod.
- I am talking about adding a new tag in this particular version of VQmod.
- Tag to define, which particular version you wand to address.
- Using "error" tag for this purpose is VERY bad practice, because you'll have to add it for EVERY entry.
- If you use error="skip", it'll hide ALL errors, even the ones you would want to be displayed. If you use error="log", you'll end up with a bunch of entries in log and you customers will bore you to death.

I really hope you'll understand my point this time.

**Comment by thekrotek** [comment]
Just a little note. This new "version" tag I'm suggesting should COMPLETELY ignore the whole entry and do NOT add anything to log, if OC version doesn't match. This is the main difference with "error" tag.

**Comment by qphoria** [comment]
No there isn't an OpenCart version of vQmod itself.. the opencart part of
that package is simply the installer and the vqmod_opencart.xml file which
is but a script. The actual vQmod class is not specific.

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by thekrotek** [comment]
OK, if you don't want to change the class specifically for OpenCart, then let's make it slightly more global. Frameworks often have their version defined in a constant like this:

`define('VERSION', '2.1.0.1');`

At least, OpenCart and Joomla do it, for the rest I'm not sure. In this case we will need 2 tags. Let's call them version-key and version-number. for OpenCart they can be used like this:

`<file name="admin/controller/common/menu.php" versionkey="VERSION" versionval="2.0">`

And before parsing the entry a single line is needed:

`if (!defined($versionkey) || !version_compare($versionkey, $versionval, '<') return;`

Yes, it won't work for everyone, but at least it'll work in cases, when framework version defined in constant. Why not?

I understand, that it's not your problem, that Daniel didn't think of any kind of backward compatibility in OpenCart. Unfortunately his attitude to developers is VERY bad, he never listens, often even being rude. So I don't have an option to talk to him on this matter. This is why I came to you for some help as a fellow developer.

There were no issues before OC 2.0 release, all was nice and shiny. Yet now we have to either deal with stupid OCMod or completely ignore it and look for other solutions, like I do. Just want to optimize my job a little and make customers' experience a little smoother.

**Comment by jktoole** [comment]
I can see where you're coming from - but still think that 2 files (one for each version) is easier for end users to understand/manage.

**Comment by thekrotek** [comment]
@jktoole, end users usually don't look into XML and can't fix even the smallest issues by themselves. And 2 files are always harder to manage than one, when they both come in one package. Most customers are non-developers, so any additional stuff may confuse them.

My suggestion will make life easier for developers only. Of course you may ignore this supposed new tag, but some people will like it, I'm sure.

I'm just a little tired of always working with 2 files. Hope OC 1.5 will die soon :-)

**Comment by qphoria** [comment]
I do understand your reasoning, but you've answered your own question here:
"Yes, it won't work for everyone, but at least it'll work in cases, when
framework version defined in constant. Why not?"

For code to be truly agnostic, it needs to work the same for everyone.
Where do you draw the line? Lets say we add a "VERSION" check
But then we branch out to Wordpress and they use "WP_VERSION"... now we
have to add 2 version tags.
Then we branch out to phpbb.. now we have to add "BB_VER" etc.

We don't want to have to add custom code for different platforms.
It is best to just ignore vQmod and treat it like an unchanging entity. Let
your code do the logic within using the version_compare function.
I've been able to get most of my vQmod scripts to work across versions this
way. It all comes down to creativity.


Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by thekrotek** [comment]
No, you do NOT need to add multiple checks for different version constants. This is what "versionkey" tag is for.

For Opencart it'll be VERSION:

`<file name="path/to/file.php" versionkey="VERSION" versionval="2.0">`

For Joomla it'll be JVERSION:

`<file name="path/to/file.php" versionkey="JVERSION" versionval="3.4">`

For Wordpress it'll be WP_VERSION:

`<file name="path/to/file.php" versionkey="WP_VERSION" versionval="4.0">`

In short, version key can be ANYTHING, it's a version constant, related to framework you're working with: OpenCart, Joomla, Wordpress, Drupal, anything. You script only has to parse versionkey and then compare it with versionval:

`if (!defined($versionkey) || !version_compare($versionkey, $versionval, '>=') return;`

That's pretty much global and can be easily implemented.

Unfortunately it's not always comes down to creativity. Sometimes you need to put your code at a very specific place, which is absolutely different for OC 1.5 and OC 2.5. Let alone different file paths, which will produce log entry with "error" tag.

**Comment by JAY6390** [comment]
@thekrotek By your very definition here, this wouldn't work. Based on
```
if (!defined($versionkey) || !version_compare($versionkey, $versionval, '>=') return;
```

If you were to have any 1.5 versions, they would execute for any versions greater than that

**Comment by thekrotek** [comment]
@JAY6390, that was just an example of how versionkey and versionval can be parsed. It's not a final solution or something. I was simply explaining, what I meant before..

**Comment by JAY6390** [comment]
OK, but lets say I have 3 values
- All of 1.5
- 2.0 to 2.1
- 2.1 or above

Then you have to do comparisons, add what type of comparison, have two separate values for it to be between. It's not just some simple addition. Considering the hundreds (this is not an exaggeration) of VQMods I've made over the last few years for versions as far back as 1.4.7, I've never had an issue where I've needed this feature. Also, I find bundling these huge numbers of code into one file a bit pointless. 2.x is so different from 1.5.x that why you'd have much if any shared code between the two I don't know, and wouldn't be able to justify that for the mammoth VQMod file you'll create as a result. I'm closing this ticket as both myself and Q don't feel this would be beneficial

**Comment by thekrotek** [comment]
You didn't feel the need, because you, probably, create several XML files, one per each version or group of versions. I do this different and have only 2 files: for OC 1.5 and OC 2.0. Ideally, I'd love to have ONE file and tell customers to just download VQMod for OpenCart and upload all the stuff on their server.

You might say "hey, create 2 packages!", but this isn't my style. I'm too lazy to create tons of packages. I used to pile everything in one XML and simplify things as much as possible. So for me such or similar tag to define OC versions is pretty much beneficial. And I'm pretty sure I'm not the only one, because we all love different things. They are not right and wrong, they are different.

You also don't find it beneficial, because you probably one of VQMod developers and, of course, you think it's perfect and suits YOUR needs. But it's definitely not beneficial to satisfy only your desires and ignore others. You like to split XML files to shorter ones for each version, I don't. You think, that OC 1.5 and 2.0 so different, that you can't find a shared code, but I see 2 almost identical versions, where whole files are just copied from version to another. I can EASILY find a common code and could create SHORTER XML file, if I had an additional version checking.

I love VQMod, I really do. And it's a pity, that we can't at least move to some common solution, but instead opposing each other.

**Comment by JAY6390** [comment]
Trust me when I say I'm all too aware of the differences between 1.5.x. Having over 30 extensions that I had to upgrade, I can say with confidence that they are not just copied. I also don't think VQMod is perfect. It's a flawed system from the start, made only as a convenience. I also don't see how you could make a shorter file as a result of this, as it would require two separate xml blocks with code for each version

**Comment by qphoria** [comment]
I agree.. in the end, especially since you want it at the <file> level, you'd end up with more code. Granted it would maybe be more easily categorized at the xml level, but actually more duplicated code since you'd be duplicating the file tag

The current way:
```
<file name="catalog/controller/module/latest.php">
	<operation>
		<search position="after"><![CDATA[function index]]></search>
		<add><![CDATA[
		if (version_compare(VERSION, '2.0', '<')) {
			$this->data['test'] = '123';
		} else {
			$data['test'] = '123';
		}
		]]></add>
	</operation>
</file>
```

Your proposed way:
```
<file name="catalog/controller/module/latest.php" versionkey="VERSION" versionval="1.5">
	<operation>
		<search position="after"><![CDATA[function index]]></search>
		<add><![CDATA[$this->data['test'] = '123';]]></add>
	</operation>
</file>

<file name="catalog/controller/module/latest.php" versionkey="VERSION" versionval="2.0">
	<operation>
		<search position="after"><![CDATA[function index]]></search>
		<add><![CDATA[$data['test'] = '123';]]></add>
	</operation>
</file>
```

Plus with your way you lose additional variations to the version or any other possible conditionals you'd like to use

**Comment by thekrotek** [comment]
@qphoria, nope, I won't loose anything. Code for 2.0 is mostly the same for all versions, but when it changes, I simply find another common string and it again works for all versions. The only time I had to add 2 absolutely similar blocks for different files was after 2.1 release, when they moved customer and customer_group models from sale to customer folder. That's it.

As for duplicated code, yes, it will be duplicated in most cases. But what's wrong with that? If I can read it, then it's OK. I don't write code to make other developers happy despite that I have pretty decent code structure, which is easy to read.

Actually, my main point behind of all this was exactly the lack of XML optimization in VQMod. For all my extensions I use my own generic controller and template files, which work on both OC major version. Unfortunately I can't do the same with XML files and instead have 2 of them for each OC version.

This is what I do in my controller, for example:

```php
if (version_compare(VERSION, '2.0', '<')) $params = $this->data;
else $params = array();

/* A bunch of generic code here */

if (version_compare(VERSION, '2.0', '<')) $this->data = $params;
else $data = $params;
```
I'd love to be able to ALWAYS do the same in XML. For your code I can easily do this even with version tags:

```xml
<file name="catalog/controller/module/latest.php">
    <operation>
        <search position="after"><![CDATA[function index]]></search>
        <add><![CDATA[

        if (version_compare(VERSION, '2.0', '<')) $this->data = $params;
        else $data = $params;

        $params['test'] = '123';

        if (version_compare(VERSION, '2.0', '<')) $this->data = $params;
        else $data = $params;

        ]]></add>
    </operation>
</file>
```
Unfortunately this will only work, if files have the same paths and search pattern present in them. For all other cases I have to create 2 XML files or add 2 code blocks with error="skip". But like I said a couple times, skipped errors leave entries in log, which confuses a lot of customers. They don't see the word SKIPPED and rush to get a support from me, which is super annoying.

In conclusion, I want to say, that my suggestion is only a suggestion. I don't insist on adding version tags, but something else is definitely needed.

Maybe it'll be a new "error" tag value - "silent", when no entries added to log, not a single character.

Maybe something else, I don't know. The general idea is to avoid creating multiple XML files for different versions with as much consequences as possible.

If you also think, that VQMod is not perfect, why can't we discuss things, but not argue?

I came here to share my ideas and experience. I have 50+ extensions only for OpenCart, but I also do develop stuff for Joomla and IP Board. There's absolutely no point in constant penis measurement contests on who did what and how many times. I'm pretty sure, we're all good, but see some things a little different. So let's just join our efforts instead of fighting.

You want me to modify VQMod myself to better demonstrate my ideas? No problem, I can do that. I just don't want to do this without any hope, that my work will be accepted, discussed, modified, not just rejected like Daniel constantly does with his issue reports.

**Comment by qphoria** [comment]
error="skip" IS a silent skip. Nothing gets written to the log
error="log" is a logged "SKIPPED"

**Comment by thekrotek** [comment]
How about this piece of code:

```php
$skip = ($mod['error'] == 'skip' || $mod['error'] == 'log') ? ' (SKIPPED)' : ' (ABORTING MOD)';
```
Yes, $skip is only added later here:

```php
if($mod['error'] == 'log' || $mod['error'] == 'abort') {
	VQMod::$log->write('VQModObject::applyMod - SEARCH NOT FOUND' . $skip . ': ' . $mod['search']->getContent(), $this);
}
```
Yet I have the entry with SEARCH NOT FOUND (SKIPPED) from time to time, even when I want it to be skipped, which means ZERO entry.

I'm confused...

**Comment by qphoria** [comment]
Yes it looks like it was set to SKIPPED on skip or log at one point, then we removed it from the actual write process.. We just didn't take it out of that initial set. Still it should never be called for "skip"

**Comment by thekrotek** [comment]
I'll try to reproduce this tomorrow. It's too late here already...

**Comment by scottw-finao** [comment]
> Again, vQmod is platform agnostic. vQmod can potentially be used with any php platform. Wordpress, phpbb, joomla, etc. It is not sensible for us to support specifics from a single platform as it is meant to be generic.

That doesn't mean you shouldn't give examples on how to plug it into more popular platforms like wordpress, phpbb, joomla, etc.

**Comment by qphoria** [comment]
> That doesn't mean you shouldn't give examples on how to plug it into more popular platforms like wordpress, phpbb, joomla, etc.

There's some hypothetical analysis of other platforms here: https://github.com/vqmod/vqmod/wiki/Integration-with-Other-Platforms

I'm not extremely familiar with other platforms so lack of experience limits any examples.
