### ISSUE TITLE
install vqmod on custom template and admin renamed folder.

### ISSUE THREAD

**Issue by Pynman** [vqmod/vqmod#80]
How to install vqmod on custom template and admin renamed folder for opencart?

**Comment by JAY6390** [comment]
https://github.com/vqmod/vqmod/wiki/Path-Aliases-(pathReplaces.php)

**Comment by qphoria** [comment]
For custom template, you use * to match any template or add a specific
<file> block for each theme

*See the Scripting page under **modification / file*

Cheers,

Tom "Qphoria"
OpenCartGuru.com
