### ISSUE TITLE
Wrong path calculated for __FILE__ and __DIR__ in modded files

### ISSUE THREAD

**Issue by nicolasblackburn** [vqmod/vqmod#83]
Using \__FILE__ and \__DIR__ constants in modded files may cause problems, due to it being replaced by the path relative to the cached modded file. However, you usually would want it to be replaced by the path of the original non-modded file. A possible fix would be to replace \__DIR__ and \__FILE__ constants in the cached modded file by the correct value corresponding to the original non-modded file.

**Comment by JAY6390** [comment]
You should really be using constants defined by your applications for paths, not relying on those. VQMod will not change any files in any way unless explicitly instructed to do so
