### ISSUE TITLE
forbidden 

### ISSUE THREAD

**Issue by ryan-noble** [vqmod/vqmod#84]
please help i have been trying to install vqmod by uploading single files but my website went down completely didnt work so after restoring it i tried this installation but i keep getting error code 403 forbidden from my server any ideas what this is about??

**Comment by JAY6390** [comment]
You need to ask your host about these errors, as they'll have error logs with more information as to what is causing the issue. Best guess is its the .htaccess file or your file permissions on the folders/files

**Comment by bkrajendra** [comment]
@ryan-noble you might have already resolved the issue. If not check this https://github.com/vqmod/vqmod/issues/70#issuecomment-621827284
