### ISSUE TITLE
Question: Memcached

### ISSUE THREAD

**Issue by supasteri** [vqmod/vqmod#85]
Hi guys

I am planning on using Opencart 2.2.0.0 for a very high volume website (ticketing website that must be able to support 1m+ concurrent users logging on and buying tickets for events). 

I am relying heavily on memcached as a replacement for the bog-standard opencart file-based caching. Was wondering if this was something that was in the pipeline for you guys for opencart in general? 

Rgds
Soteri

**Comment by JAY6390** [comment]
Not really sure why this is being asked here, as it has nothing to do with VQMod from what I can tell?

**Comment by supasteri** [comment]
Apologies, my question was in reference to vqmod not opencart. I apologise if the question was confusing.

**Comment by JAY6390** [comment]
Still not sure why this would be related to VQMod - the caching used for VQMod is file based and contained within the /vqmod/directory itself. It doesn't in any way use the OpenCart caching
