### ISSUE TITLE
Call to undefined method Front::addPostAction()

### ISSUE THREAD

**Issue by awill-oyova** [vqmod/vqmod#86]
After upgrading the opencart module from version 2.2.1 to version 2.6.1 the site went down with this error (only the front facing site went down, admin worked fine):

Fatal error: Call to undefined method Front::addPostAction() in /index.php on line 234

The code on that line is:
`$controller->addPostAction(new Action('common/seo_content'));`

I wasn't able to fine the function in the Front class, however that line of code worked fine before the upgrade. Upon doing research I saw that the issue may have been my install of vqmod, so if you could give me any help on this issue or let me know if i installed it wrong it would be greatly appreciated.

**Comment by qphoria** [comment]
Unrelated to vQmod. This is something in your index file added after vqmod
stuff is already done executing

**Comment by awill-oyova** [comment]
Ok, thanks for your help.
