### ISSUE TITLE
opencart site admin not found after install

### ISSUE THREAD

**Issue by harap** [vqmod/vqmod#87]
Hello,

After installing vqmod, my site admin page become un-accessable with the following error:
-------------------------------------------------------------------------------------------
Warning: require_once(./vqmod/vqmod.php): failed to open stream: No such file or directory in /home/mysite.com/admin/index.php on line 17
Fatal error: require_once(): Failed opening required './vqmod/vqmod.php' (include_path='.:/usr/local/lib/php:/usr/local/php5/lib/pear') in /home/mysite/admin/index.php on line 17
--------------------------------------------------------------------------------------------
It was created vqmod/vqcache. The OC store front everything looks normal, but admin page.

Please help. 

Thanks in advance!

**Comment by JAY6390** [comment]
There should be an extra `.` at the beginning of `./vqmod/vqmod.php`. I've only ever seen this when people have copied the main index.php to the admin folder, which won't work. Regardless this isn't a bug - the installer works just fine

**Comment by harap** [comment]
I tested with extra .still won't work.

Thanks.

**Comment by qphoria** [comment]
Where did you put the extra dot? Should be ../vqmod/vqmod.php in the admin
index

**Comment by harap** [comment]
Yes. I did. Not working

**Comment by JAY6390** [comment]
Then you have not installed the vqmod directory in the right location. Watch the install video on how to do so

**Comment by harap** [comment]
Hi,

I reinstalled. checked mysite.com/vqmod/install/ get VQMOD READY INSTALLED
message.

These folders and files permission checked:
vqmod 0777
index.php 0777
admin 0777
admin/index.php 0777
vqmod/vqcache 0777

But admin site url still failed with following error:
----------------------------------------------------------------------------------------
Notice: Undefined index: token in /home/
mysite.com/admin/controller/error/not_found.php on line 16Notice: Undefined
index: token in /home/xxx.com/admin/controller/error/not_found.php on line
21

Fatal error: Call to a member function getUserName() on null in /home/
mysite.com/admin/controller/common/header.php on line 41
---------------------------------------------------------------------------------------

Please help. Thanks in advance!


Best regards,

*Mike *

--------------------------------------------------

**Comment by JAY6390** [comment]
Hi Mike

Those are not related in any way to VQMod and by the look of it you have VQMod installed correctly now

Jay

**Comment by harap** [comment]
Thank you Jay.

I have to remove VQMod otherwise I can't access my admin site. Any
suggestion to solve this problem?

I did try and installed that called VQMOD PRO extension before yours, but I
already removed them. Don't know if that extension changed or damaged those
error files.

Thanks in advance!

Best regards,

*Mike Young*

--------------------------------------------------

**Comment by qphoria** [comment]
Please email me with ftp access
qphoria-at-gmail-d0t-com

and I'll take a look at what is going on there.

Q

**Comment by harap** [comment]
Thank you for your help. I can't provide ftp because too much problem.

When I removed vqmod and put the original OC files back, then my admin site
comeback to normal. So I think the error is caused by vqmod.

Best regards,

*Mike Young*
--------------------------------------------------

**Comment by harap** [comment]
Hello Sir,

For your reference, I installed Easy VQMOD Installer instead, and done.
Just uploaded their vqmod fold with doing anything else (except for if you
change admin folder name).
Every looks good so far.

I asked for help for your vqcom on OC. Should I mark resolved by other
VQMOD ?

Thank you for your time.

Best regards,

*Mike Young*

--------------------------------------------------
