### ISSUE TITLE
wrong path generate 

### ISSUE THREAD

**Issue by mthsialkot** [vqmod/vqmod#88]
I have custom theme in opencart
when I installed new extension 
I received this error not loaded file 
/public_html/catalog/view/theme/default/template**/default/template/**module/formillalivechat.tpl! in /home/mthcompk/public_html/vqmod/vqcache/vq2-system_storage_modification_system_library_template_basic.php on line 26

generate twice default/template

**Comment by JAY6390** [comment]
Does it happen just with that modules code, or with all items? If it's just that module.. then it's the module creating the issue due to them calling their template incorrectly

**Comment by qphoria** [comment]
When you see the default/template/default/template generated twice, that
means you are trying to run a 2.1.x or older mod on OpenCart 2.2.0.0. In
2.2.0.0, the template function changed and needs to be updated before you
can use that module. This is not related to vQmod engine.

Q

**Comment by mthsialkot** [comment]
OK Thanks

Best regards,
Multi Trading House
First & secure online shop in Sialkot Pakistan.
http://www.sialkotshop.com
admin@sialkotshop.com
