### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by donguillermo** [vqmod/vqmod#89]
Hello,

I run OC 2.0.1.1.
I followed the instructions here : https://github.com/vqmod/vqmod/wiki/Installing-vQmod-on-OpenCart

 -I uploaded vqmod folder at my root folder, and made sure that the permissions were ok. I realized that the vqmod/vqcache was missing, so I created it.

Then when I realized that the folder vqmod/vqcache was missing... so i created it.
I ran the install successfully.
But vqmod/vqcache remains empty.

What should I doto solve this ?

Thank you !

**Comment by JAY6390** [comment]
The vqcache folder will create itself if the permissions are correct. It sounds like they're not. Also, check that the file /vqmod/xml/vqmod_opencart.xml is present. If it isn't, add it. If none of the above works, we offer an installation service for $15. Contact me - jay [at] jaygilford [dot] com if you'd like us to install for you

Kind regards
Jay

**Comment by donguillermo** [comment]
Hi Jay,

For some reason, some files were copied incompletely to the destination folder... so i reuploaded it, and it created the vqcache.

Thanks for your help, I certainly appreciate !

**Comment by JAY6390** [comment]
No problem. Glad it's solved 👍
