### ISSUE TITLE
preg_replace(): The /e modifier is deprecated

### ISSUE THREAD

**Issue by zohaibbadarpura** [vqmod/vqmod#91]
preg_replace_callback instead in /home3/logolov1/public_html/vqmod/vqmod.php on line 247Unknown: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /home3/logolov1/public_html/vqmod/vqmod.php on line 247Unknown: preg_replace(): The /e modifier is deprecated, use 

Getting this error on my Opencart 1.5.3 with vqmod..... How to fix this issue.

check this link.
http://www.fashiondezine.com/

**Comment by JAY6390** [comment]
The error explains the issue - you are using the /e modifier in a regular expression. This has been deprecated for years and needs removing. I expect you may be using a very outdated vqmod version

**Comment by zohaibbadarpura** [comment]
Give me the example.... How Can I Replace it??

on line 247	$modFilePath = preg_replace('/([^*]+)/e', 'preg_quote("$1", "~")', $modFilePath);

**Comment by JAY6390** [comment]
You need to upgrade VQMOD. There are details in the wiki on how to do this

**Comment by zohaibbadarpura** [comment]
I tried updating .... endup with this

www.fashiondezine.com/vqmod/install/

**Comment by qphoria** [comment]
Now you have a different error on your site

Cheers,

Tom "Qphoria"
OpenCartGuru.com
