### ISSUE TITLE
Error: Could not load template...

### ISSUE THREAD

**Issue by jainy25** [vqmod/vqmod#92]
A newbie here with Opencart. But pretty sure I did all the steps right as far installing vqmod is concerned. Even got the success message. 

However, now I only see this on my home page - 

Notice: Error: Could not load template /home/ilvg/public_html/catalog/view/theme/default/template/default/template/common/footerright.tpl! in /home/ilvg/public_html/vqmod/vqcache/vq2-system_library_template_php.php on line 23

Using Opencart 2.3.0.2.

**Comment by JAY6390** [comment]
Hi

You have installed VQMod correctly. However, you've uploaded an xml to your /vqmod/xml/ directory for an extension, and by the looks of it you've not uploaded a template for it. You'll need to do so or remove the xml file. This is nothing to do with us and you'll need to contact the developer of the extension to figure this out

Kind regards
Jay

**Comment by qphoria** [comment]
As stated before, when you see the double
"default/template/default/template" that means you are trying to use a
2.1.x mod with opencart 2.2.x or later. You need to ask the author for a
2.2.x version of the script
