### ISSUE TITLE
Support for DIR_MODIFICATION outside webroot

### ISSUE THREAD

**Issue by davidteal** [vqmod/vqmod#93]
Hi guys.

For our OpenCart clients, we move the storage folder out of the web root for security reasons. We've just noticed an issue on Windows where vQmod tries to create cache files using the full path of the directory including C:\ etc.  Similar to issue #81 but that didn't fix this issue.

You can test this using OpenCart 2.3.* and vQmod 2.6.1 and move the storage folder outside the web root. Obviously is you don't plan to support doing this, then we will just have to keep the modification folder under system/storage but it would be easier to just move the whole folder.

Thanks.

**Comment by JAY6390** [comment]
Hi David

This is unlikely to be supported to be honest. The paths used by vqmod are relative to the webroot, and so it's not possible to use paths outside of this

Kind regards
Jay

**Comment by susanlummis** [comment]
I am currently away and will return on 12th September.  For anything urgent please contact steve@puckator.co.uk

**Comment by davidteal** [comment]
That's a shame but no problem.

Thanks.
