### ISSUE TITLE
Cant modify files with underscore in the name

### ISSUE THREAD

**Issue by nikksan** [vqmod/vqmod#97]
For axample:
`<file name="catalog/controller/common/seo_url.php">
       <operation error="skip" info="">
           <search position="after"><![CDATA[
              class ControllerCommonLanguage
           ]]></search>
           <add><![CDATA[ 
              private $das;
           ]]></add>
       </operation>
   </file>`
does not work.
However ,
`<file name="catalog/controller/common/language.php">
       <operation error="skip" info="">
           <search position="after"><![CDATA[
              class ControllerCommonLanguage
           ]]></search>
           <add><![CDATA[ 
              private $das;
           ]]></add>
       </operation>
   </file> `
works.

**Comment by JAY6390** [comment]
It works with underscores just fine. You have the wrong controller in the first examples search tag

**Comment by nikksan** [comment]
The controller was not executing.
My Bad.
